import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

import { describe, expect, it } from 'vitest';

/**
 * Deleted features stay deleted, and dead data sources stay dead.
 *
 * This repo tears things out deliberately — dump stations, travel style, the
 * vehicle-remediation wizard, stop photos, the trip-wide fuel fan-out, the
 * fuel-pricing layer, OSM Overpass and OSRM. Each removal is a paragraph in
 * CLAUDE.md, and a paragraph cannot stop the next person reintroducing the name.
 *
 * The one that proves the point: `a0c9ee6` moved Finn from OSM/OSRM to Google
 * Places on 2026-07-22, and for seven weeks CLAUDE.md still said OSM, "free".
 * An assistant read that, relayed it as fact, built a fuel cascade on the belief
 * that the calls were free, and wrote the false rationale back into CLAUDE.md.
 * The same seven weeks left `/privacy` telling users their fuel-station data
 * went to OpenStreetMap when it was going to Google — a false disclosure in a
 * legal document, which is what this guard would have caught on the day.
 *
 * COMMENTS ARE STRIPPED BEFORE SCANNING, and that is the whole design. "Replaces
 * the OSM Overpass client" in `google/places.ts` is TRUE and worth keeping;
 * `polyline.ts` legitimately names the OSRM polyline encoding, because that is
 * the format's name and Google uses it too. What must not exist is the thing
 * itself: an import, an identifier, a hostname, or a sentence rendered to a
 * user. So this reads code and JSX text, never prose about code.
 */

const ROOT = join(__dirname, '..', '..');
const SCAN_DIRS = ['src', 'mobile'];

/** Where a name is allowed to survive, and why. Each entry is a decision. */
const ALLOW: { file: string; term: string; why: string }[] = [
  {
    file: 'src/server/db/schema.ts',
    term: 'StopPhoto',
    why: 'stops.photos is a DORMANT column, kept until a later migration drops it (CLAUDE.md, "Stop photos — fully removed"). The type stays with the column.',
  },
];

function walk(dir: string, out: string[] = []): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const name of entries) {
    const p = join(dir, name);
    if (name === 'node_modules' || name.startsWith('.')) continue;
    if (statSync(p).isDirectory()) {
      // mobile/shared is generated by sync-shared from src; scanning it would
      // report every finding twice.
      if (relative(ROOT, p) === 'mobile/shared') continue;
      walk(p, out);
    } else if (/\.tsx?$/.test(name) && !/\.test\.tsx?$/.test(name)) {
      out.push(p);
    }
  }
  return out;
}

/**
 * Blank out comments so prose about a removed thing survives but the thing does
 * not. Replaces with spaces rather than deleting, so reported line numbers stay
 * true.
 */
export function stripComments(src: string): string {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
    .replace(/(^|[^:])\/\/[^\n]*/g, (m, p1) => p1 + ' '.repeat(m.length - p1.length));
}

/** Each forbidden term, with the removal it belongs to. */
const FORBIDDEN: { term: RegExp; what: string }[] = [
  { term: /dump_station|dumpStation/i, what: 'dump stations (migration 0015)' },
  { term: /travel_style|travelStyle/i, what: 'travel style (migration 0014)' },
  { term: /vehicleRemediation|needs_vehicle_profile_remediation/i, what: 'the vehicle-remediation wizard (migration 0014)' },
  { term: /StopPhoto/, what: 'stop photos (2026-06-30)' },
  { term: /replenishFuelStopsForTrip/, what: 'the trip-wide fuel fan-out (2026-07-02)' },
  { term: /fuelPricing|tankerkoenig/i, what: 'the fuel-pricing layer (a0c9ee6)' },
  { term: /overpass/i, what: 'OSM Overpass as a station source (a0c9ee6 — Finn is Google Places)' },
  { term: /\bosrm\b/i, what: 'OSRM as a routing source (a0c9ee6 — routing is Google Directions)' },
];

const files = SCAN_DIRS.flatMap((d) => walk(join(ROOT, d)));

describe('removed features stay removed', () => {
  it('finds source files to scan', () => {
    expect(files.length).toBeGreaterThan(100);
  });

  for (const { term, what } of FORBIDDEN) {
    it(`no live reference to ${what}`, () => {
      const hits: string[] = [];
      for (const file of files) {
        const rel = relative(ROOT, file);
        if (rel.endsWith('removedFeaturesGuard.test.ts')) continue;
        const code = stripComments(readFileSync(file, 'utf8'));
        code.split('\n').forEach((line, i) => {
          if (!term.test(line)) return;
          const allowed = ALLOW.some(
            (a) => a.file === rel && term.test(a.term)
          );
          if (allowed) return;
          hits.push(`${rel}:${i + 1}: ${line.trim().slice(0, 110)}`);
        });
      }
      expect(hits, `Removed: ${what}. Comments are stripped, so these are live.`).toEqual([]);
    });
  }
});

describe('the comment stripper the guard relies on', () => {
  it('blanks line and block comments but keeps code', () => {
    expect(stripComments('const a = 1; // overpass').trim()).toBe('const a = 1;');
    expect(stripComments('/* overpass */ const a = 1;').trim()).toBe('const a = 1;');
    expect(stripComments("const a = 'overpass';")).toContain('overpass');
  });

  it('keeps line numbers stable', () => {
    expect(stripComments('a\n/* x\ny */\nb').split('\n')).toHaveLength(4);
  });

  it('does not eat a URL inside a string', () => {
    // `https://…` contains `//`; the negative lookbehind on `:` is what saves it.
    expect(stripComments("const u = 'https://places.googleapis.com/v1';")).toContain(
      'places.googleapis.com'
    );
  });
});
