-- Two-level itinerary grouping. Until now `legs` has been used as the only
-- itinerary entity, even though Penny's intent has been "one leg per driving
-- day". Users describe trips at a coarser grain — "Girona → Berlin" might be
-- one user-stated jump that takes 5 driving days. The UI now wants to render
-- short trips as a flat list of days but long/multi-destination trips as
-- segments (the user's stated jumps) containing the days underneath.
--
-- This migration adds two optional columns on `legs` so we don't have to
-- introduce a new table for v1:
--
--   segment_index INTEGER  → stable per-trip ordering of segments. All days
--                            in the same user-stated jump share this value.
--                            NULL = leg is not assigned to any segment, which
--                            is the only state for legs created before this
--                            migration ran.
--
--   segment_name  TEXT     → the user-readable label for the segment, e.g.
--                            "Girona → Berlin". Denormalized across the days
--                            that belong to the segment so we don't need a
--                            join to render headers.
--
-- We deliberately use ALTER TABLE ADD COLUMN (no NOT NULL, no default) so the
-- migration is fast and lock-light on existing rows. Backfilling segment data
-- for legacy trips is out of scope here — UI renders those as a flat list.
--
-- Promotion path: if we later need real segment-level metadata (segment
-- notes, segment-level Maps URL, segment dates beyond what fits on a single
-- leg row), the natural next step is a `trip_segments` table with the legs
-- pointing at it via segment_id. The columns here become a denormalized cache
-- of that table, or we drop them and migrate the values into the new table.

ALTER TABLE "legs" ADD COLUMN IF NOT EXISTS "segment_index" integer;--> statement-breakpoint
ALTER TABLE "legs" ADD COLUMN IF NOT EXISTS "segment_name" text;
