import { expect, type Page } from '@playwright/test';

/**
 * E2E authentication — the real sign-in flow, minus the mailbox.
 *
 * Every test signs in as a FRESH user: mint a unique fixture address, submit
 * it on /login, read the code the app just generated from the guarded
 * `/api/test/otp` endpoint, and type it into the real six-box verify UI.
 * `signInWithOtp` find-or-creates the user, so seeding fixture data for the
 * same email before OR after login both work.
 *
 * WHY NOT AN INBOX (2026-08-15): the suite used MailSlurp, whose free trial
 * expired and cannot be renewed; then a Google Workspace mailbox over IMAP,
 * which cost an afternoon on app passwords, alias-vs-user and Workspace
 * policy without ever authenticating. Both were third parties who could — and
 * did — switch the pipeline off. Eleven of the twelve specs never cared about
 * email; they needed a signed-in user.
 *
 * WHAT THIS IS NOT: a sign-in bypass. Nothing is minted and nothing is
 * granted. The code is generated by the real /login request, stored with its
 * real expiry, submitted through the real form, and checked by the real
 * verifyOtpCode with its attempt limits. The endpoint is 404 unless
 * E2E_TEST_ENDPOINTS=1 (never true on production, no override), requires the
 * per-run HMAC secret, and refuses any address outside FIXTURE_EMAIL_PATTERN.
 * The old AUTH_TEST_BACKDOOR — which minted sessions outright, for any user —
 * is still gone and `src/lib/noBackdoorGuard.test.ts` still fails the build if
 * it returns.
 *
 * WHAT THIS PATH DOES NOT COVER: that Resend actually delivers, and that the
 * email template contains a code a human can read. e2e/login-otp.spec.ts
 * covers exactly that, on every PR, through a real mailbox on a Resend
 * receiving domain (fixtures/mailbox.ts). The split is the point: eleven specs
 * that need a signed-in user take the cheap path, and one spec does real mail
 * — so a mail problem reds ONE spec instead of switching the pipeline off,
 * which is what happened in August. E2E_MAX_SKIPPED is the backstop against a
 * spec quietly ceasing to run; drop it to 0 once E2E_INBOX_DOMAIN is set.
 */

/** Addresses live on a subdomain with no MX: they can never receive mail. */
const FIXTURE_DOMAIN = 'e2e.feraltravels.com';

export interface FreshUser {
  email: string;
  tag: string;
}

let seq = 0;

/**
 * Mint a fresh user address. No network, so this cannot fail or skip.
 * The run id makes it obvious which CI run produced a row when one is left
 * behind; the counter and timestamp keep specs from colliding.
 */
export function createFreshUser(): FreshUser {
  const runId = (process.env.GITHUB_RUN_ID || `local${process.pid}`).toLowerCase();
  const tag = `${runId}-${Date.now().toString(36)}-${seq++}`;
  return { email: `playwright-${tag}@${FIXTURE_DOMAIN}`, tag };
}

/**
 * Poll for the code the app stored when /login was submitted.
 *
 * Polling rather than a single read because the code is written by the request
 * the browser just made, and the navigation resolving doesn't guarantee the
 * insert has landed.
 */
export async function readOtpCode(
  page: Page,
  email: string,
  opts: { timeoutMs?: number } = {}
): Promise<string> {
  const deadline = Date.now() + (opts.timeoutMs ?? 20_000);
  let lastStatus = 0;
  let lastBody = '';

  while (Date.now() < deadline) {
    const res = await page.request.post('/api/test/otp', { data: { email } });
    lastStatus = res.status();
    if (res.ok()) {
      const body = (await res.json()) as { code?: string | null };
      if (body.code) return body.code;
      lastBody = 'code not written yet';
    } else {
      lastBody = await res.text().catch(() => '');
      // 404 means the endpoint is off, or the secret didn't match — no amount
      // of polling fixes either.
      if (lastStatus === 404) break;
    }
    await page.waitForTimeout(500);
  }

  throw new Error(
    `[e2e/auth] No OTP for ${email} (last status ${lastStatus}${lastBody ? `: ${lastBody}` : ''}). ` +
      `404 means E2E_TEST_ENDPOINTS=1 is missing on the target, or the x-e2e-test-secret header ` +
      `doesn't match E2E_TEST_ENDPOINTS_SECRET. 400 means the address didn't match the fixture pattern.`
  );
}

/** Drive the real OTP UI flow for `user` and land on `redirectTo`. */
export async function loginViaOtp(
  page: Page,
  user: FreshUser,
  opts: { redirectTo?: string } = {}
): Promise<void> {
  const redirectTo = opts.redirectTo || '/trips';

  await page.goto(`/login?callbackUrl=${encodeURIComponent(redirectTo)}`);
  await page.locator('input[name="email"]').fill(user.email);
  await Promise.all([
    page.waitForURL(/\/login\/verify/, { timeout: 15_000 }),
    page.getByRole('button', { name: /email me a code/i }).click(),
  ]);

  const code = await readOtpCode(page, user.email);

  const target = redirectTo.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  await submitOtpCode(page, code, new RegExp(`${target}(\\?|$)`));
}

/**
 * Enter the six digits and wait to land on `landingUrl`.
 *
 * WHY THIS IS NOT JUST `keyboard.type(code)` (2026-08-15): it was, and every
 * authenticated spec failed against the Vercel preview while passing locally.
 * The failure snapshots showed all six boxes EMPTY after 30s with no error
 * banner — the form had never been submitted, because the keystrokes were
 * delivered before React hydrated. Characters typed into a server-rendered
 * input that nothing is listening to are discarded the moment hydration
 * replaces the value with controlled state. Locally the app is interactive
 * almost instantly so the race never showed; a cold preview is slow enough to
 * lose every time.
 *
 * WHY THE FIRST FIX DIDN'T TAKE (2026-08-17): it retried the entry and asserted
 * `box(5)` held its value, reasoning that "a box that holds its value is direct
 * proof React is listening". It is not. A pre-hydration DOM write satisfies that
 * assertion identically, because nothing has overwritten the value yet — and
 * box 5 is the box that ALWAYS survives, since by the fifth fill React is live.
 * The guard could never fail on the thing it was guarding against.
 *
 * The error-context snapshots from CI run 32012644704 show what actually
 * happens: digit 1 EMPTY, digits 2-6 filled, Verify disabled, no error banner.
 * Only the FIRST fill lands pre-hydration. It goes into the DOM, hydration then
 * re-renders the controlled input from empty state and wipes it, `codeComplete`
 * never flips, and the form is never submitted.
 *
 * So gate on a signal only React can produce, then verify every box we filled.
 * verify-form.tsx focuses box 1 from a mount effect, and an effect cannot run
 * before hydration — that is real proof of interactivity. A value assertion on
 * a controlled input never is.
 *
 * NOTE (2026-08-17): this race was latent long before it fired. The MailSlurp
 * era awaited real email delivery between landing on /login/verify and the
 * first keystroke — an accidental sleep that guaranteed hydration had finished.
 * /api/test/otp returns in milliseconds, which removed the sleep, not the bug.
 *
 * Only the first five are retried. Six digits triggers the form's auto-submit
 * (the `codeComplete` effect in verify-form.tsx), which navigates away and
 * would make a retry race a page that no longer exists. So five prove the form
 * is live, then the sixth fires the submit.
 */
export async function submitOtpCode(
  page: Page,
  code: string,
  landingUrl: RegExp
): Promise<void> {
  const box = (n: number) => page.locator(`input[aria-label="Digit ${n} of 6"]`);
  await expect(box(1)).toBeVisible({ timeout: 15_000 });
  // The mount effect that focuses box 1 cannot run before React has hydrated,
  // so this is the hydration gate. Do not weaken it to a value assertion.
  await expect(box(1)).toBeFocused({ timeout: 30_000 });

  await expect(async () => {
    for (let i = 1; i <= 5; i++) await box(i).fill(code[i - 1]);
    // Every box we filled, not just the last: box 1 is the one that gets wiped.
    for (let i = 1; i <= 5; i++) await expect(box(i)).toHaveValue(code[i - 1]);
  }).toPass({ timeout: 30_000, intervals: [250, 500, 1000, 2000] });

  await Promise.all([
    page.waitForURL(landingUrl, { timeout: 30_000 }),
    box(6).fill(code[5]),
  ]);
}

/** One-call setup used by most specs: fresh user + real OTP login. */
export async function loginAsFreshUser(
  page: Page,
  opts: { redirectTo?: string } = {}
): Promise<FreshUser> {
  const user = createFreshUser();
  await loginViaOtp(page, user, opts);
  return user;
}
