import { expect, type Page } from '@playwright/test';
// A static import. This was `await import('./test-trip')` inside
// signInAsNewUser, and under the runner's CJS transform that intermittently
// threw "Cannot use import statement outside a module" — the spec then failed
// before it had opened a page. test-trip.ts imports nothing from this file,
// so there is no cycle to work around.
import { seedCanonicalFixture } from './test-trip';

/**
 * Signing in, the way a user does it.
 *
 *   1. type a unique email on /login and submit
 *   2. read the code the app just generated, from /api/test/otp
 *   3. type the six digits into the real verify form
 *   4. land on the page we asked for
 *
 * No bypass and nothing minted: the code is generated by the real /login
 * request, stored with its real expiry, and checked by the real verifyOtpCode.
 * /api/test/otp replaces the mailbox, not a step of authentication — it is 404
 * unless E2E_TEST_ENDPOINTS=1 (never true on production, no override), requires
 * the per-run secret, and refuses any address outside the fixture pattern.
 *
 * e2e/login-otp.spec.ts covers the part this skips: that Resend actually
 * delivers a readable code to a real inbox.
 */

/** Fixture addresses live on a subdomain with no MX — they can never reach a person. */
const FIXTURE_DOMAIN = 'e2e.feraltravels.com';

let seq = 0;

/** A fresh address, unique per run and per call. */
export function uniqueEmail(): string {
  const runId = (process.env.GITHUB_RUN_ID || `local${process.pid}`).toLowerCase();
  return `playwright-${runId}-${Date.now().toString(36)}-${seq++}@${FIXTURE_DOMAIN}`;
}

/** Back-compat shape for specs that want the object form. */
export function createFreshUser(): { email: string } {
  return { email: uniqueEmail() };
}

/**
 * Read the code the app stored when /login was submitted. Polls, because the
 * navigation resolving doesn't guarantee the insert has landed yet.
 */
export async function readOtpCode(page: Page, email: string): Promise<string> {
  const deadline = Date.now() + 20_000;
  let lastStatus = 0;
  let lastBody = '';

  while (Date.now() < deadline) {
    const res = await page.request.post('/api/test/otp', { data: { email } });
    lastStatus = res.status();
    if (res.ok()) {
      const body = (await res.json()) as { code?: string | null };
      if (body.code) return body.code;
      lastBody = 'code not written yet';
    } else {
      lastBody = await res.text().catch(() => '');
      if (lastStatus === 404) break; // endpoint off or wrong secret — polling won't help
    }
    await page.waitForTimeout(500);
  }

  throw new Error(
    `[e2e/auth] No OTP for ${email} (last status ${lastStatus}${lastBody ? `: ${lastBody}` : ''}). ` +
      `404 means E2E_TEST_ENDPOINTS=1 is missing on the target, or x-e2e-test-secret ` +
      `doesn't match E2E_TEST_ENDPOINTS_SECRET. 400 means the address didn't match the fixture pattern.`,
  );
}

/**
 * Type the six digits and land on `landingUrl`.
 *
 * Retried, and that is load-bearing. /login/verify hits a React hydration
 * mismatch on the preview (errors #418/#425 -> #423, "the entire root switches
 * to client rendering"), so React throws away the server DOM and rebuilds it a
 * beat after load. Anything typed before that moment is in a node that no
 * longer exists — which reliably ate digit 1 and left a form that could never
 * submit, because `codeComplete` was never true.
 *
 * Refilling until every box holds its value survives that, and would survive
 * any other cause too. Assert ALL five, not just the last: box 5 always
 * survives (React is live by then) and checking only box 5 is what let this
 * through twice. The sixth digit is filled last, outside the retry, because it
 * triggers the form's auto-submit and navigates away.
 *
 * If the hydration mismatch is ever fixed, this stays correct — it just stops
 * needing a second attempt.
 */
export async function submitOtpCode(page: Page, code: string, landingUrl: RegExp): Promise<void> {
  const box = (n: number) => page.getByLabel(`Digit ${n} of 6`);
  await expect(box(1)).toBeVisible({ timeout: 15_000 });

  await expect(async () => {
    for (let i = 1; i <= 5; i++) await box(i).fill(code[i - 1]);
    for (let i = 1; i <= 5; i++) await expect(box(i)).toHaveValue(code[i - 1]);
  }).toPass({ timeout: 30_000, intervals: [250, 500, 1000, 2000] });

  await Promise.all([
    page.waitForURL(landingUrl, { timeout: 30_000 }),
    box(6).fill(code[5]),
  ]);
}

/**
 * Sign in as `email` and land on `redirectTo`. This is the whole login flow.
 */
export async function login(
  page: Page,
  email: string,
  redirectTo: string = '/trips',
): Promise<void> {
  await page.goto(`/login?callbackUrl=${encodeURIComponent(redirectTo)}`);

  await page.getByPlaceholder('you@example.com').fill(email);
  await Promise.all([
    page.waitForURL(/\/login\/verify/, { timeout: 15_000 }),
    // `/email me a/i`, not the full sentence: the button reads "Email me a
    // 6-digit code" since the sign-in rebuild, and the old
    // `/email me a code/i` could not match across the inserted words. The
    // click then never landed and the 15s waitForURL above rejected first,
    // so all 36 web specs failed with a navigation timeout that said nothing
    // about a button. Match the stable part of the label.
    page.getByRole('button', { name: /email me a/i }).click(),
  ]);

  const code = await readOtpCode(page, email);

  const target = redirectTo.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  await submitOtpCode(page, code, new RegExp(`${target}(\\?|$)`));
}

/** Back-compat wrapper for the object form. */
export async function loginViaOtp(
  page: Page,
  user: { email: string },
  opts: { redirectTo?: string } = {},
): Promise<void> {
  await login(page, user.email, opts.redirectTo || '/trips');
}

/**
 * The standard opening line: a brand-new user, its fixture graph seeded, signed
 * in and sitting on `redirectTo`. Returns the email so the spec can seed more
 * of its own data.
 *
 * One user per test is what makes `fullyParallel` safe — no spec can see or
 * disturb another spec's rows.
 */
export async function signInAsNewUser(
  page: Page,
  opts: { redirectTo?: string; seedFixture?: boolean } = {},
): Promise<string> {
  const email = uniqueEmail();
  if (opts.seedFixture !== false) await seedCanonicalFixture(email);
  await login(page, email, opts.redirectTo || '/trips');
  return email;
}
