import { type Page } from '@playwright/test';

/**
 * E2E authentication — the real sign-in flow, minus the mailbox.
 *
 * Every test signs in as a FRESH user: mint a unique fixture address, submit
 * it on /login, read the code the app just generated from the guarded
 * `/api/test/otp` endpoint, and type it into the real six-box verify UI.
 * `signInWithOtp` find-or-creates the user, so seeding fixture data for the
 * same email before OR after login both work.
 *
 * WHY NOT AN INBOX (2026-08-15): the suite used MailSlurp, whose free trial
 * expired and cannot be renewed; then a Google Workspace mailbox over IMAP,
 * which cost an afternoon on app passwords, alias-vs-user and Workspace
 * policy without ever authenticating. Both were third parties who could — and
 * did — switch the pipeline off. Eleven of the twelve specs never cared about
 * email; they needed a signed-in user.
 *
 * WHAT THIS IS NOT: a sign-in bypass. Nothing is minted and nothing is
 * granted. The code is generated by the real /login request, stored with its
 * real expiry, submitted through the real form, and checked by the real
 * verifyOtpCode with its attempt limits. The endpoint is 404 unless
 * E2E_TEST_ENDPOINTS=1 (never true on production, no override), requires the
 * per-run HMAC secret, and refuses any address outside FIXTURE_EMAIL_PATTERN.
 * The old AUTH_TEST_BACKDOOR — which minted sessions outright, for any user —
 * is still gone and `src/lib/noBackdoorGuard.test.ts` still fails the build if
 * it returns.
 *
 * WHAT THIS PATH DOES NOT COVER: that Resend actually delivers, and that the
 * email template contains a code a human can read. e2e/login-otp.spec.ts
 * covers exactly that, on every PR, through a real mailbox on a Resend
 * receiving domain (fixtures/mailbox.ts). The split is the point: eleven specs
 * that need a signed-in user take the cheap path, and one spec does real mail
 * — so a mail problem reds ONE spec instead of switching the pipeline off,
 * which is what happened in August. E2E_MAX_SKIPPED is the backstop against a
 * spec quietly ceasing to run; drop it to 0 once E2E_INBOX_DOMAIN is set.
 */

/** Addresses live on a subdomain with no MX: they can never receive mail. */
const FIXTURE_DOMAIN = 'e2e.feraltravels.com';

export interface FreshUser {
  email: string;
  tag: string;
}

let seq = 0;

/**
 * Mint a fresh user address. No network, so this cannot fail or skip.
 * The run id makes it obvious which CI run produced a row when one is left
 * behind; the counter and timestamp keep specs from colliding.
 */
export function createFreshUser(): FreshUser {
  const runId = (process.env.GITHUB_RUN_ID || `local${process.pid}`).toLowerCase();
  const tag = `${runId}-${Date.now().toString(36)}-${seq++}`;
  return { email: `playwright-${tag}@${FIXTURE_DOMAIN}`, tag };
}

/**
 * Poll for the code the app stored when /login was submitted.
 *
 * Polling rather than a single read because the code is written by the request
 * the browser just made, and the navigation resolving doesn't guarantee the
 * insert has landed.
 */
export async function readOtpCode(
  page: Page,
  email: string,
  opts: { timeoutMs?: number } = {}
): Promise<string> {
  const deadline = Date.now() + (opts.timeoutMs ?? 20_000);
  let lastStatus = 0;
  let lastBody = '';

  while (Date.now() < deadline) {
    const res = await page.request.post('/api/test/otp', { data: { email } });
    lastStatus = res.status();
    if (res.ok()) {
      const body = (await res.json()) as { code?: string | null };
      if (body.code) return body.code;
      lastBody = 'code not written yet';
    } else {
      lastBody = await res.text().catch(() => '');
      // 404 means the endpoint is off, or the secret didn't match — no amount
      // of polling fixes either.
      if (lastStatus === 404) break;
    }
    await page.waitForTimeout(500);
  }

  throw new Error(
    `[e2e/auth] No OTP for ${email} (last status ${lastStatus}${lastBody ? `: ${lastBody}` : ''}). ` +
      `404 means E2E_TEST_ENDPOINTS=1 is missing on the target, or the x-e2e-test-secret header ` +
      `doesn't match E2E_TEST_ENDPOINTS_SECRET. 400 means the address didn't match the fixture pattern.`
  );
}

/** Drive the real OTP UI flow for `user` and land on `redirectTo`. */
export async function loginViaOtp(
  page: Page,
  user: FreshUser,
  opts: { redirectTo?: string } = {}
): Promise<void> {
  const redirectTo = opts.redirectTo || '/trips';

  await page.goto(`/login?callbackUrl=${encodeURIComponent(redirectTo)}`);
  await page.locator('input[name="email"]').fill(user.email);
  await Promise.all([
    page.waitForURL(/\/login\/verify/, { timeout: 15_000 }),
    page.getByRole('button', { name: /email me a code/i }).click(),
  ]);

  const code = await readOtpCode(page, user.email);

  const firstDigit = page
    .locator('input[aria-label="Digit 1 of 6"]')
    .or(page.locator('input[autocomplete="one-time-code"]'))
    .first();
  await firstDigit.click();
  // Six single-char boxes that auto-advance on keystroke — fill() would dump
  // all six digits into box 1 (→ InvalidCode). Type real keystrokes instead.
  const target = redirectTo.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  await Promise.all([
    page.waitForURL(new RegExp(`${target}(\\?|$)`), { timeout: 30_000 }),
    page.keyboard.type(code),
  ]);
}

/** One-call setup used by most specs: fresh user + real OTP login. */
export async function loginAsFreshUser(
  page: Page,
  opts: { redirectTo?: string } = {}
): Promise<FreshUser> {
  const user = createFreshUser();
  await loginViaOtp(page, user, opts);
  return user;
}
