/**
 * Expo config as JS (not app.json) so build-time env can reach the native
 * layer — specifically the Google Maps iOS SDK key, which react-native-maps
 * needs baked into the binary, and the reversed Google OAuth client id, which
 * has to be a registered URL scheme for the native sign-in redirect to come
 * back to the app.
 *
 * Everything degrades: with no Google keys the map falls back to Apple Maps
 * and the Google sign-in button hides itself rather than dead-ending.
 */
const GOOGLE_IOS_CLIENT_ID = process.env.EXPO_PUBLIC_GOOGLE_IOS_CLIENT_ID || null;
const APPLE_SIGNIN = process.env.EXPO_PUBLIC_ENABLE_APPLE_SIGNIN === '1';

// Google's iOS OAuth redirect scheme is the client id with its dot-segments
// reversed: 123-abc.apps.googleusercontent.com -> com.googleusercontent.apps.123-abc
const reversedClientId = GOOGLE_IOS_CLIENT_ID
  ? GOOGLE_IOS_CLIENT_ID.split('.').reverse().join('.')
  : null;

module.exports = {
  expo: {
    name: 'Feral Travels',
    slug: 'feral-travels',
    owner: 'samuelashirley',
    // EAS project link. app.config.js is a dynamic config, so `eas init`
    // cannot write this itself — it must be maintained by hand.
    extra: {
      eas: { projectId: '8228a0d9-1f26-4a3a-bcf0-aa86d90c3886' },
    },
    // EAS Update. Written by hand because `eas build` cannot edit a
    // dynamic config; the URL is derived from the projectId above.
    updates: {
      url: 'https://u.expo.dev/8228a0d9-1f26-4a3a-bcf0-aa86d90c3886',
    },
    // appVersion policy: an OTA update only reaches builds sharing the
    // same `version`, so a native change can never be handed JS that
    // expects a different native surface.
    runtimeVersion: { policy: 'appVersion' },
    version: '1.0.0',
    scheme: 'feraltravels',
    icon: './assets/icon.png',
    orientation: 'portrait',
    userInterfaceStyle: 'automatic',
    newArchEnabled: true,
    ios: {
      bundleIdentifier: 'com.feraltravels.ios',
      supportsTablet: false,
      // Guideline 4.8: offering Google sign-in obliges us to offer Sign in
      // with Apple as well. But the entitlement this flag adds requires a
      // provisioning profile, which turns every local build into a
      // code-signing problem — and Apple sign-in cannot be exercised on a
      // simulator without a team anyway. Opt in when building for a device or
      // TestFlight: EXPO_PUBLIC_ENABLE_APPLE_SIGNIN=1 npx expo prebuild --clean
      // AppleAuthentication.isAvailableAsync() returns false without it, so
      // the button hides itself rather than dead-ending.
      ...(APPLE_SIGNIN ? { usesAppleSignIn: true } : {}),
      config: {
        // Only set when present — an empty string makes the Google map render
        // as a blank grey rectangle, which is worse than falling back to Apple.
        ...(process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY
          ? { googleMapsApiKey: process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY }
          : {}),
      },
      /**
       * PrivacyInfo.xcprivacy, authored HERE rather than left to the prebuild.
       *
       * `mobile/ios/` is gitignored — it is generated by `expo prebuild` and
       * regenerated with `--clean` on every build, local and EAS. So the
       * manifest that shipped up to now was Expo's stock bare-minimum template:
       * correct, but invisible, unreviewable, un-diffable, and one Expo release
       * away from changing under us with nothing to notice. `ios.privacyManifests`
       * is @expo/config-plugins' supported seam and it MERGES into the template
       * (see its `mergePrivacyInfo`: API types union by category and union their
       * reason arrays; collected data types union by type), so declaring the
       * four categories the template already carries is a no-op on today's
       * output and a floor under tomorrow's.
       *
       * ── Required-reason APIs ─────────────────────────────────────────────
       *
       * This is the half that BLOCKS AN UPLOAD (ITMS-91053, "Missing API
       * declaration"). Every code below was read off the manifests of the
       * dependencies actually on disk, not recalled:
       *
       *   FileTimestamp   C617.1  metadata of files in the app's own container
       *                   0A2A.1  a third-party SDK doing the same on our behalf
       *                   3B52.1  files the user specifically granted access to
       *   UserDefaults    CA92.1  our own defaults, readable only by this app
       *   DiskSpace       E174.1  write/delete when space is low
       *                   85F4.1  display available space
       *   SystemBootTime  35F9.1  time elapsed between events inside the app
       *
       * None of these are calls our JavaScript makes. They belong to React
       * Native, Hermes and the Expo modules compiled into the app target, which
       * is exactly why the app target has to declare them — a dependency's own
       * manifest covers the dependency's binary, not ours.
       *
       * Nothing was added speculatively. `DDA9.1` (showing file timestamps to
       * the user) and `8FFB.1` (absolute event timestamps) are absent because
       * this app does neither, and a reason you do not use is a claim you
       * cannot defend.
       *
       * ── Collected data ───────────────────────────────────────────────────
       *
       * Apple's rule is that this array need not cover third-party SDKs the app
       * links to — because those ship their own manifest and Apple aggregates
       * across all of them. THAT RULE HAS A PRECONDITION worth checking rather
       * than assuming: the SDK's manifest has to actually reach the built
       * product. A pod whose .xcprivacy is not in a resource bundle contributes
       * nothing, and its code is compiled into the app target anyway. See the
       * PurchaseHistory row below for the one that turned out that way here.
       *
       * So this is OUR collection plus anything linked-in that nothing else
       * declares, and it is the same eight rows as the nutrition-label table in
       * docs/design/app-store-listing.md §4, deliberately: two descriptions of
       * what this app collects that can drift apart is one too many. Change one
       * and change the other — and the App Store Connect questionnaire with
       * them.
       *
       * `Linked: true` throughout — every one of these hangs off `users.id`.
       * `Tracking: false` throughout, and `NSPrivacyTracking: false` below,
       * because there is no ad network, no analytics SDK and no data broker in
       * the build. That answer stops being true the day one is added, and the
       * ASC privacy questionnaire has to move with it.
       */
      privacyManifests: {
        NSPrivacyTracking: false,
        // No domain in this build is contacted for tracking. An empty array is
        // the affirmative answer, not an omission.
        NSPrivacyTrackingDomains: [],
        NSPrivacyAccessedAPITypes: [
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryFileTimestamp',
            NSPrivacyAccessedAPITypeReasons: ['C617.1', '0A2A.1', '3B52.1'],
          },
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryUserDefaults',
            NSPrivacyAccessedAPITypeReasons: ['CA92.1'],
          },
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategoryDiskSpace',
            NSPrivacyAccessedAPITypeReasons: ['E174.1', '85F4.1'],
          },
          {
            NSPrivacyAccessedAPIType: 'NSPrivacyAccessedAPICategorySystemBootTime',
            NSPrivacyAccessedAPITypeReasons: ['35F9.1'],
          },
        ],
        NSPrivacyCollectedDataTypes: [
          // Sign-in. Every account is keyed by a verified address, whether it
          // arrived by six-digit code, Google, or Apple — including a
          // @privaterelay.appleid.com alias, which is still an address we store.
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeEmailAddress',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          // Optional and provider-supplied: Google's `name` claim, or the one
          // Apple hands over on the FIRST authorization only. An OTP-only
          // account never has one.
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeName',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          // Precise, and it has to be: the progress anchor is "I am HERE now",
          // and Finn's tank walk is metres-sensitive. `DeviceLocationContext`
          // is the only thing in the app that may call the Geolocation API.
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypePreciseLocation',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          // expo-image-picker, from ChatPanel's attach button. User-initiated
          // every time; there is no background or bulk read of the library.
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypePhotosorVideos',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          // The trips themselves: chat with Penny, itineraries, stops, vehicle
          // profiles. The substance of the product.
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeOtherUserContent',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          // `users.id`. Also what goes to RevenueCat as `app_user_id` — see
          // mobile/lib/purchases.ts for why it must be that and nothing else.
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeUserID',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          /**
           * What was bought, and when it ends.
           *
           * TRUE OF OUR OWN SERVER INDEPENDENTLY OF ANY SDK, which is why it
           * belongs here and is not somebody else's row to declare:
           * `subscriptions` stores `product_id`, `original_transaction_id` and
           * `current_period_end` keyed on `users.id` as its PRIMARY KEY, and
           * `subscription_events` keeps the store's verbatim payload beside it.
           * `Linked: true` follows from that — RevenueCat's own manifest says
           * `false` because an `app_user_id` is pseudonymous to them, but it is
           * our primary key, so it is linked for us.
           *
           * It was missing, and the reason it was missing is worth keeping:
           * `react-native-purchases` ships no manifest in npm at all, and the
           * two pods it pulls (`RevenueCat`, `PurchasesHybridCommon`) DO ship
           * one each — `Pods/RevenueCat/Sources/PrivacyInfo.xcprivacy` and the
           * PurchasesHybridCommon equivalent — and NEITHER REACHES THE BUILT
           * PRODUCT. Checked three ways against a real `pod install`, not
           * assumed: `Pods.xcodeproj` has `ResourceBundle-*_privacy` targets for
           * React-Core, React-cxxreact, ExpoApplication, ExpoConstants and
           * ExpoFileSystem and none for either of those two; the string
           * `RevenueCat/Sources/PrivacyInfo.xcprivacy` appears nowhere in
           * `project.pbxproj`; and no script under `Target Support Files`
           * copies it. So nothing aggregates them and the app target is the
           * only thing that can speak for that code. (Their required-reason usage is UserDefaults `CA92.1`,
           * already declared above — so this was never an ITMS-91053 risk, only
           * an incomplete nutrition label.)
           */
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypePurchaseHistory',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
          /**
           * The stream-error beacon, and nothing else.
           *
           * `ChatPanel`'s `reportStreamError` POSTs to
           * `/api/analytics/client-error` when Penny's SSE stream dies — a
           * short code, the phase, whether the app was backgrounded, and up to
           * 500 characters of the error's own text. The route requires a
           * session and writes it to `usage_events` WITH a `user_id`, so it is
           * linked whether or not it is interesting.
           *
           * "Other Diagnostic Data" rather than "Crash Data": nothing here
           * crashes, and there is no crash reporter in the build. There is also
           * no analytics SDK — `/api/analytics/viewport-time` exists but the
           * app never calls it (grepped; only the web does), which is why
           * Product Interaction is absent from this list. The day the app
           * starts calling it, this list and §4 of the listing doc both grow a
           * row.
           */
          {
            NSPrivacyCollectedDataType: 'NSPrivacyCollectedDataTypeOtherDiagnosticData',
            NSPrivacyCollectedDataTypeLinked: true,
            NSPrivacyCollectedDataTypeTracking: false,
            NSPrivacyCollectedDataTypePurposes: [
              'NSPrivacyCollectedDataTypePurposeAppFunctionality',
            ],
          },
        ],
      },
      infoPlist: {
        // No custom cryptography: HTTPS only. Declaring it here stops App
        // Store Connect asking on every single upload.
        ITSAppUsesNonExemptEncryption: false,
        NSLocationWhenInUseUsageDescription:
          'Feral Travels uses your location to anchor your trip progress and plan fuel stops along your route.',
        NSPhotoLibraryUsageDescription:
          'Feral Travels lets you attach photos to your messages with Penny so she can see what you are looking at.',
        ...(reversedClientId
          ? { CFBundleURLTypes: [{ CFBundleURLSchemes: [reversedClientId] }] }
          : {}),
      },
    },
    android: {
      /**
       * DELIBERATELY STILL `.app`, while iOS moved to `.ios` (2026-09-02).
       *
       * The rename was forced by Apple and applies only to Apple: uploading a
       * TestFlight build binds a bundle id to the developer account that
       * uploaded it, permanently, so `com.feraltravels.app` cannot be used
       * again on the new team. Nothing about that touches Google Play, where
       * this id has never been published and is not bound to anything.
       *
       * Changing it here would be a second rename with no reason behind it. If
       * the two should match for tidiness that is a decision to make on
       * purpose, not a side effect of Apple's rule.
       */
      package: 'com.feraltravels.app',
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: '#55346F',
      },
    },
    plugins: [
      'expo-router',
      [
        'expo-splash-screen',
        {
          // splash-icon.png is the master art verbatim. An earlier revision
          // feathered its edges into transparency to hide the vignette seam;
          // contain-mode rendered that feather as a halo on device. Plain
          // square, flat background, no alpha.
          image: './assets/splash-icon.png',
          imageWidth: 300,
          resizeMode: 'contain',
          backgroundColor: '#55346F',
        },
      ],
      'expo-secure-store',
      'expo-web-browser',
      ...(APPLE_SIGNIN ? ['expo-apple-authentication'] : []),
      [
        'expo-location',
        {
          locationAlwaysAndWhenInUsePermission:
            'Feral Travels uses your location to anchor your trip progress and plan fuel stops along your route.',
        },
      ],
      [
        'expo-image-picker',
        {
          photosPermission:
            'Feral Travels lets you attach photos to your messages with Penny so she can see what you are looking at.',
        },
      ],
    ],
    experiments: { typedRoutes: true },
  },
};
