'use client';

import { useCallback, useEffect, useState } from 'react';

/**
 * Spin up a disposable paywalled account, from the admin page.
 *
 * This was a separate `/admin/test-users` page first, and that was wrong: it
 * was one form behind a navigation, on a dashboard whose whole point is that
 * everything is on one screen. It is a block near the bottom now.
 *
 * WHAT IT DOES NOT DO: sign you in as the account. The auth guard test in
 * `src/lib/` fails the suite on anything resembling a sign-in bypass, and an
 * admin impersonation action in production is exactly what it exists to
 * prevent. What this removes is the MAILBOX — the code below is real,
 * generated by the real sender, and has to be typed into the real verify form
 * and checked by the real verifier with its expiry and attempt limits intact.
 * Open the link in a private window and type it. Ten seconds, your own session
 * untouched.
 */

type Preset = {
  id: string;
  label: string;
  hint: string;
  withTrip: boolean;
};

/**
 * Two, because the difference between them is the only one that changes what
 * the paywall has to do: an account with no trips lands on Penny with nothing
 * behind her, an account with one has an itinerary to be held out of. Other
 * states (subscribed, cancelled, over the cap) are reachable from the account
 * page and do not belong in a one-click generator.
 */
const PRESETS: Preset[] = [
  {
    id: 'day7-trip',
    label: 'Day 7, with a trip',
    hint: 'Trial just ended, twelve-day itinerary behind the wall. The main one.',
    withTrip: true,
  },
  {
    id: 'day7-empty',
    label: 'Day 7, no trip',
    hint: 'Trial ended before they ever planned anything — lands straight on Penny.',
    withTrip: false,
  },
];

interface Created {
  email: string;
  code: string | null;
  link: string;
}

export default function TestUserBlock({
  armed,
  paywallOn,
}: {
  armed: boolean;
  /**
   * `paywallEnabled()` on the server that rendered this page.
   *
   * Here because of the afternoon this block cost. A `day7-trip` account was
   * generated in production, signed into, and walked end to end: no overlay on
   * /trips, nothing locked on the trip, no bubble from Penny, and "+ New trip"
   * still worked. Every one of those is `applySwitch` doing its job — with
   * `PAYWALL_ENABLED` unset it rewrites every verdict to entitled, so the
   * account WAS `trial_expired` the whole time and nothing was ever allowed to
   * act on it. The state was right; the switch was off.
   *
   * No test could have caught it: `e2e/subscriptions.spec.ts` deploys its
   * preview with `PAYWALL_ENABLED=1` precisely so the walls appear, so the
   * suite is green and production is unenforced at the same time, correctly.
   * The gap is not coverage, it is that the one screen whose entire purpose is
   * to produce a blocked account never said whether blocking was switched on.
   * It says so now, before you spend ten minutes proving the switch is off.
   */
  paywallOn: boolean;
}) {
  const [preset, setPreset] = useState(PRESETS[0].id);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [created, setCreated] = useState<Created | null>(null);
  const [accounts, setAccounts] = useState<{ email: string; createdAt: string }[]>([]);
  const [copied, setCopied] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    if (!armed) return;
    try {
      const res = await fetch('/api/admin/test-users');
      if (!res.ok) return;
      const data = await res.json();
      setAccounts(data.accounts ?? []);
    } catch {
      // A failed list is not worth an error banner — the generator still works.
    }
  }, [armed]);

  useEffect(() => {
    void refresh();
  }, [refresh]);

  async function generate() {
    const chosen = PRESETS.find((p) => p.id === preset)!;
    setBusy(true);
    setError(null);
    setCreated(null);
    try {
      const res = await fetch('/api/admin/test-users', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'create',
          ageDays: 7,
          subscription: null,
          withTrip: chosen.withTrip,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? 'Could not create the account');
      const email: string = data.account.email;
      setCreated({
        email,
        code: data.code ?? null,
        link: `${window.location.origin}/login/verify?email=${encodeURIComponent(email)}`,
      });
      void refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not create the account');
    } finally {
      setBusy(false);
    }
  }

  async function act(email: string, action: 'delete' | 'resend') {
    try {
      const res = await fetch('/api/admin/test-users', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action, email }),
      });
      const data = await res.json();
      if (action === 'resend') {
        // 429 still carries the pending code — it is valid, just not new.
        setCreated({
          email,
          code: data.code ?? null,
          link: `${window.location.origin}/login/verify?email=${encodeURIComponent(email)}`,
        });
        if (!res.ok && !data.code) setError(data.error ?? 'Could not send a code');
        return;
      }
      if (!res.ok) throw new Error(data.error ?? 'Failed');
      if (created?.email === email) setCreated(null);
      void refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed');
    }
  }

  function copy(value: string, key: string) {
    void navigator.clipboard?.writeText(value).then(() => {
      setCopied(key);
      setTimeout(() => setCopied((c) => (c === key ? null : c)), 1400);
    });
  }

  if (!armed) {
    return (
      <p style={{ fontSize: 12, color: 'var(--tp-subtle)', margin: 0, lineHeight: 1.5 }}>
        Set <code style={mono}>SUBSCRIPTION_TESTING=1</code> in this environment to switch this on.
        It defaults to off, and the server refuses to create an account without it. Leave it unset
        in production once real purchases are live — the accounts this makes carry{' '}
        <code style={mono}>source: &apos;fake&apos;</code> subscriptions nobody paid for.
      </p>
    );
  }

  const chosen = PRESETS.find((p) => p.id === preset)!;

  return (
    <div>
      {/*
        First thing in the block, and deliberately not a footnote. An account
        generated while this is off is not a paywall test — it is a normal
        account with an old `created_at`, and it will walk every surface
        without hitting anything.
      */}
      {!paywallOn && (
        <p
          data-testid="test-users-paywall-off"
          style={{
            margin: '0 0 12px',
            padding: '8px 10px',
            borderRadius: 8,
            border: '1px solid var(--tp-border-strong)',
            background: 'var(--tp-surface-2, transparent)',
            fontSize: 12,
            lineHeight: 1.55,
            color: 'var(--tp-text)',
          }}
        >
          <strong>The paywall is switched off in this environment.</strong> Accounts made here will
          still be <code style={mono}>trial_expired</code> and the account page will still say so,
          but <code style={mono}>applySwitch</code> hands every verdict full access, so nothing will
          block: no overlay on <code style={mono}>/trips</code>, no lock on the trip, no bubble from
          Penny. Set <code style={mono}>PAYWALL_ENABLED=1</code> on this deployment to walk a real
          wall. It is an env change, not a deploy.
        </p>
      )}
      <div style={{ display: 'flex', gap: 8, alignItems: 'flex-start', flexWrap: 'wrap' }}>
        <select
          value={preset}
          onChange={(e) => setPreset(e.target.value)}
          disabled={busy}
          aria-label="Test account type"
          style={{
            padding: '7px 10px',
            borderRadius: 8,
            border: '1px solid var(--tp-border)',
            background: 'var(--tp-surface)',
            color: 'var(--tp-text)',
            fontSize: 13,
            minWidth: 200,
          }}
        >
          {PRESETS.map((p) => (
            <option key={p.id} value={p.id}>
              {p.label}
            </option>
          ))}
        </select>
        <button
          type="button"
          onClick={() => void generate()}
          disabled={busy}
          style={{
            padding: '7px 14px',
            borderRadius: 8,
            border: 'none',
            background: busy ? 'var(--tp-border)' : 'var(--tp-primary)',
            color: busy ? 'var(--tp-subtle)' : 'var(--tp-on-primary)',
            fontSize: 13,
            fontWeight: 700,
            cursor: busy ? 'default' : 'pointer',
          }}
        >
          {busy ? 'Generating…' : 'Generate test user'}
        </button>
      </div>
      <p style={{ fontSize: 11, color: 'var(--tp-subtle)', margin: '8px 0 0', lineHeight: 1.5 }}>
        {chosen.hint}
      </p>

      {error ? (
        <p role="alert" style={{ fontSize: 12, color: 'var(--tp-danger)', margin: '10px 0 0' }}>
          {error}
        </p>
      ) : null}

      {created ? (
        <div
          style={{
            marginTop: 12,
            padding: 12,
            borderRadius: 8,
            border: '1px solid var(--tp-border)',
            background: 'var(--tp-surface-muted)',
            display: 'grid',
            gap: 8,
          }}
        >
          <Field label="Email" value={created.email} onCopy={() => copy(created.email, 'email')} copied={copied === 'email'} />
          <Field
            label="Code"
            value={created.code ?? 'send failed — use “New code”'}
            onCopy={created.code ? () => copy(created.code!, 'code') : undefined}
            copied={copied === 'code'}
          />
          <Field label="Sign-in link" value={created.link} onCopy={() => copy(created.link, 'link')} copied={copied === 'link'} />
          <p style={{ fontSize: 11, color: 'var(--tp-subtle)', margin: 0, lineHeight: 1.5 }}>
            Open the link in a private window and type the code. The code expires — press{' '}
            <strong>New code</strong> below if it goes stale. It is also in the{' '}
            <code style={mono}>sam@feraltravels.com</code> inbox.
          </p>
        </div>
      ) : null}

      {accounts.length > 0 ? (
        <div style={{ marginTop: 14 }}>
          <div style={{ fontSize: 10, letterSpacing: 0.6, color: 'var(--tp-subtle)', fontWeight: 700, marginBottom: 6 }}>
            EXISTING ({accounts.length})
          </div>
          <div style={{ display: 'grid', gap: 4 }}>
            {accounts.map((a) => (
              <div
                key={a.email}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  gap: 10,
                  fontSize: 12,
                  padding: '5px 0',
                  borderBottom: '1px solid var(--tp-border)',
                }}
              >
                <code style={{ ...mono, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {a.email}
                </code>
                <span style={{ display: 'flex', gap: 10, flexShrink: 0 }}>
                  <button type="button" onClick={() => void act(a.email, 'resend')} style={linkBtn}>
                    New code
                  </button>
                  <button
                    type="button"
                    onClick={() => void act(a.email, 'delete')}
                    style={{ ...linkBtn, color: 'var(--tp-danger)' }}
                  >
                    Delete
                  </button>
                </span>
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  );
}

function Field({
  label,
  value,
  onCopy,
  copied,
}: {
  label: string;
  value: string;
  onCopy?: () => void;
  copied: boolean;
}) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, minWidth: 0 }}>
      <span style={{ fontSize: 10, letterSpacing: 0.6, color: 'var(--tp-subtle)', fontWeight: 700, width: 74, flexShrink: 0 }}>
        {label.toUpperCase()}
      </span>
      <code style={{ ...mono, flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
        {value}
      </code>
      {onCopy ? (
        <button type="button" onClick={onCopy} style={{ ...linkBtn, flexShrink: 0 }}>
          {copied ? 'Copied' : 'Copy'}
        </button>
      ) : null}
    </div>
  );
}

const mono: React.CSSProperties = {
  fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
  fontSize: 12,
};

const linkBtn: React.CSSProperties = {
  background: 'none',
  border: 'none',
  padding: 0,
  color: 'var(--tp-primary)',
  fontSize: 11,
  fontWeight: 700,
  cursor: 'pointer',
};
