import 'server-only';
import { randomBytes } from 'node:crypto';
import { and, desc, eq, gt, isNotNull, sql } from 'drizzle-orm';
import { db } from '@/server/db/client';
import {
  chatHistory,
  emailOtpCodes,
  legs,
  subscriptions,
  trips,
  usageAlerts,
  usageEvents,
  users,
} from '@/server/db/schema';
import { addVehicle } from '@/server/repos/vehicles';
import { HILUX_FIXTURE_VEHICLE } from '@/app/api/test/fixtureVehicle';
import { cloneTrip, createTrip } from '@/server/repos/trips';
import { seededTripStartISO } from '@/app/api/test/seedDates';
// The real greeting, imported rather than retyped: a fixture whose first turn
// differs from the one every real trip opens with is a fixture that can pass
// while the thing it stands in for has changed underneath it.
import { TRIP_INTENT_QUESTION } from '@/server/onboarding';
import { legDateISO } from '@/lib/dates';
import type { SubscriptionStatus } from '@/types/entitlement';
import { TEST_PURCHASE_EMAIL_PATTERN, testPurchasesArmed } from './testPurchase';
import { TRIAL_DAYS } from './constants';

/**
 * Disposable accounts for walking the paywall, created from /admin/test-users.
 *
 * WHAT THIS DOES NOT DO, and will not: mint a session, set an auth cookie, or
 * shorten sign-in by one step. The auth guard test in `src/lib/` fails the unit
 * suite if anything in `src/` starts to look like that, and it is right to —
 * it caught an earlier draft of THIS comment, which named the guard file and
 * so contained the very word it scans for. An admin "sign in as this user"
 * button is precisely what it exists to prevent, and building one would mean
 * the app's strongest security claim — that authentication happens exactly
 * three ways — stops being true in production, permanently, to save a browser
 * tab.
 *
 * What it removes is the MAILBOX, not authentication. The code is generated by
 * the real `sendOtpCode`, stored with its real expiry, and has to be typed into
 * the real six-box verify form and validated by the real `verifyOtpCode` with
 * its attempt limits intact. `/api/test/otp` makes exactly this argument for
 * the E2E suite; this is the same trade for the same reason.
 *
 * Showing the code to an admin grants nothing anyway: these addresses are
 * `sam+trial-<tag>@feraltravels.com`, the mail is already being delivered to
 * the inbox the admin is reading, and the pattern is hardcoded where no env
 * var can widen it. The admin guard on top is cookie-only, allowlist +
 * verified email + DB flag.
 *
 * Everything here refuses any address outside that pattern, and everything is
 * additionally off unless `SUBSCRIPTION_TESTING=1`.
 */

export class NotATestAccountError extends Error {
  constructor(email: string) {
    super(`${email} is not a test account address`);
  }
}

function assertArmed(): void {
  if (!testPurchasesArmed()) {
    throw new Error('SUBSCRIPTION_TESTING is not set — test accounts are disabled here');
  }
}

/**
 * Exported, because the route needs it BEFORE it calls anything else.
 *
 * The resend action reaches `sendOtpCode` directly and returns the code it
 * generates. Without this check in front of it, an admin could type any user's
 * address and be handed a working sign-in code for their account — the admin
 * panel would have become the account-takeover tool the rest of this codebase
 * is carefully built not to contain. The pattern is the boundary; it has to be
 * checked on the path that bypasses the helpers below, not only inside them.
 */
export function assertTestAddress(email: string): string {
  const normalized = email.trim().toLowerCase();
  if (!TEST_PURCHASE_EMAIL_PATTERN.test(normalized)) throw new NotATestAccountError(normalized);
  return normalized;
}

/**
 * A fresh address per creation, never a reused one.
 *
 * Reusing an address does not test a trial, it tests an aged account carrying
 * the last run's trips, usage and — fatally — a subscription row, at which
 * point `created_at` decides nothing and the paywall never appears no matter
 * how far back it is pushed. The random suffix rather than a bare timestamp is
 * so two creations in the same minute cannot collide into the same account.
 */
export function generateTestEmail(now = new Date()): string {
  const stamp = now.toISOString().slice(2, 10).replace(/-/g, '');
  return `sam+trial-${stamp}-${randomBytes(2).toString('hex')}@feraltravels.com`;
}

export interface CreateTestAccountInput {
  /** How old the account should look. 7 puts it exactly on the paywall. */
  ageDays: number;
  /** Null means no subscription row at all — the trial is then the only thing deciding. */
  subscription: SubscriptionStatus | null;
  /** Days until `current_period_end`. Negative puts the period in the past. */
  periodEndsInDays?: number;
  autoRenew?: boolean;
  /** Synthetic Anthropic spend in whole dollars, for the trial ceiling and cap states. */
  spendUsd?: number;
  /**
   * Give the account a real, populated trip.
   *
   * A paywalled account with NO trips and one with a trip are different
   * screens — the first lands on Penny with nothing behind her, the second has
   * an itinerary to be blocked out of — so both need to be one click away.
   */
  withTrip?: boolean;
}

export interface TestAccountSummary {
  id: string;
  email: string;
  createdAt: Date;
  subscriptionStatus: SubscriptionStatus | null;
  spendMicrocents: number;
}

/**
 * Create the user row directly. This is NOT a sign-in — the row exists with
 * `emailVerified` null and no session, exactly as if somebody had been invited
 * and never turned up.
 *
 * Creating it here rather than letting the first sign-in create it is what
 * makes the age stick: `createSessionForEmail` finds an existing row and
 * patches only `emailVerified`, so the `created_at` set below survives the
 * sign-in that follows. Do it the other way round and the row is born with
 * `defaultNow()` and has to be aged afterwards, which is one more step to
 * forget.
 */
export async function createTestAccount(input: CreateTestAccountInput): Promise<TestAccountSummary> {
  assertArmed();
  const email = generateTestEmail();
  const createdAt = new Date(Date.now() - input.ageDays * 24 * 60 * 60 * 1000);

  const [row] = await db
    .insert(users)
    .values({
      email,
      createdAt,
      // Deliberately NOT verified. The real OTP sign-in stamps this; setting it
      // here would be the app asserting something no one has proved.
      emailVerified: null,
      name: 'Paywall test account',
    })
    .returning({ id: users.id });

  const spendMicrocents = Math.round((input.spendUsd ?? 0) * 100_000_000);
  if (spendMicrocents > 0) {
    await db.insert(usageEvents).values({
      userId: row.id,
      // Must start with `anthropic` or the cap query (`LIKE 'anthropic%'`)
      // will not count it and the state under test never occurs. Must be
      // unmistakably synthetic, because previews clone production data.
      provider: 'anthropic:admin-test-account',
      model: 'synthetic',
      requests: 1,
      costMicrocents: spendMicrocents,
    });
  }

  if (input.subscription) {
    const periodEnd =
      input.periodEndsInDays === undefined
        ? null
        : new Date(Date.now() + input.periodEndsInDays * 24 * 60 * 60 * 1000);
    await db.insert(subscriptions).values({
      userId: row.id,
      status: input.subscription,
      source: 'fake',
      productId: 'com.feraltravels.ios.annual',
      currentPeriodEnd: periodEnd,
      autoRenew: input.autoRenew ?? true,
    });
  }

  if (input.withTrip) await seedRealisticAccountData(row.id);

  return {
    id: row.id,
    email,
    createdAt,
    subscriptionStatus: input.subscription,
    spendMicrocents,
  };
}

/**
 * Make the account look like one a person could actually have.
 *
 * The first version of this cloned a trip and stopped, and the result was data
 * the app itself cannot produce: `cloneTrip` hardcodes `vehicleId: null` and
 * leaves the clone at `onboarding_state: 'not_started'`, so a brand-new
 * account got a trip full of legs while owning no vehicle and never having
 * onboarded. Signed into, it showed Penny's "Hi, I'm Penny, let's plan a trip"
 * greeting above a finished twelve-day itinerary, and every day read "Finish
 * your vehicle profile — no vehicle on file for user".
 *
 * None of that was a bug in the paywall, the chat or Finn. All three were
 * behaving correctly for a state that had no business existing. A fixture that
 * writes rows directly is the only thing that can build it, which is exactly
 * why nothing else caught it.
 *
 * So this seeds all four facts a real account holds together, in order:
 *   1. a vehicle, and one that can actually fuel-plan (the Hilux numbers)
 *   2. the trip, cloned so the legs and stops are real, re-dated forward
 *   3. that trip pointed at that vehicle, and marked onboarded
 *   4. the user-level onboarding stamp, so a seed can be ASKED whether it
 *      built something coherent
 *
 * It re-dates the clone forward for the reason `seedDates.ts` spells out: a
 * past-dated trip is a different product state, and a tester who wanted the
 * planning flow would get the archive instead.
 */
async function seedRealisticAccountData(userId: string): Promise<void> {
  const startISO = seededTripStartISO();

  // 1. The vehicle FIRST. Everything downstream — the trip's vehicle_id, the
  //    onboarding stamp, Finn's first check — is a lie without it.
  const vehicle = await addVehicle(userId, {
    name: HILUX_FIXTURE_VEHICLE.name,
    range_km: HILUX_FIXTURE_VEHICLE.range_km,
    fuel_type: HILUX_FIXTURE_VEHICLE.fuel_type,
    is_default: true,
  });

  const [source] = await db
    .select({ id: trips.id, start: trips.startDateParsed, end: trips.endDateParsed })
    .from(trips)
    .innerJoin(users, eq(users.id, trips.userId))
    .where(and(eq(users.isAdmin, true), isNotNull(trips.startDateParsed)))
    .orderBy(desc(trips.createdAt))
    .limit(1);

  let tripId: string;
  let endISO: string | null = null;

  if (source) {
    tripId = await cloneTrip(source.id, userId);
    // Preserve the source's DURATION while moving its start, so the clone
    // still resembles the trip it came from.
    const days =
      source.start && source.end
        ? Math.max(
            0,
            Math.round(
              (new Date(source.end).getTime() - new Date(source.start).getTime()) / 86_400_000
            )
          )
        : null;
    endISO = days === null ? null : legDateISO(startISO, days);

    // A transcript, because a finished itinerary with an empty one is the other
    // half of the same tell — Penny plans in conversation, so a trip she
    // supposedly planned has one.
    //
    // GENERATED, not cloned. Copying the source trip's rows across was the
    // obvious way to do it and it put a lie in the fixture: the source chat is
    // a real conversation about real calendar dates, so a clone of it arrived
    // saying "setting off Tue 18 Aug" and "change this trip to me leaving on
    // September 15th" above an itinerary this function had just re-dated to
    // today + 14. Reported as a bug in the seeded dates; the dates were right
    // and the conversation about them was three weeks stale. `plan_summary` is
    // worse still — it is a snapshot of depart/arrive dates that the UI renders
    // INSTEAD of the prose, so a cloned one puts stale dates on screen as
    // structured fact rather than as something Penny once said.
    //
    // The generated turns say only what is true of the trip that now exists,
    // and they say it in terms of `startISO`, so the fixture cannot rot the way
    // a calendar date written into a row does.
    await db.insert(chatHistory).values(seedTranscript(tripId, startISO, await routeNames(tripId)));
  } else {
    const created = await createTrip({ userId, name: 'Test trip', startDate: startISO });
    tripId = created.id;
  }

  // 3 + 4. The trip points at the vehicle and is past onboarding; the account
  //        is stamped as having onboarded. `cloneTrip` does neither, and its
  //        not doing so is correct for the user-facing clone button — this is
  //        the fixture layer's job to finish.
  await db
    .update(trips)
    .set({
      name: 'Test trip',
      tripNameCiKey: 'test trip',
      vehicleId: vehicle.id,
      onboardingState: 'done',
      startDate: startISO,
      startDateParsed: startISO,
      endDate: endISO,
      endDateParsed: endISO,
    })
    .where(eq(trips.id, tripId));

  await db
    .update(users)
    .set({ onboardingCompletedAt: new Date() })
    .where(eq(users.id, userId));
}


/**
 * The route the seeded trip actually describes, as the ordered list of places
 * it stops at, de-duplicated.
 *
 * Read from the legs that were just cloned rather than hardcoded, because the
 * source trip is whatever the admin's most recent one is and that changes. A
 * transcript naming towns the itinerary does not visit is the same class of
 * fixture lie this function exists to stop telling.
 */
async function routeNames(tripId: string): Promise<string[]> {
  const rows = await db
    .select({ start: legs.startName, end: legs.endName })
    .from(legs)
    .where(eq(legs.tripId, tripId))
    .orderBy(legs.sortOrder);

  const names: string[] = [];
  for (const r of rows) {
    for (const n of [r.start, r.end]) {
      const name = n?.trim();
      // Consecutive duplicates only: a rest day is start === end, and a route
      // that legitimately returns to where it started should say so at the end.
      if (name && name !== names[names.length - 1]) names.push(name);
    }
  }
  return names;
}

/** "Thu 10 Sep" — the form Penny writes a departure in. UTC, like every seed. */
function humanDate(iso: string): string {
  return new Date(`${iso}T00:00:00Z`).toLocaleDateString('en-GB', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    timeZone: 'UTC',
  });
}

/**
 * The four turns that make a seeded trip look planned.
 *
 * Every date in them is derived from `startISO`, which is itself
 * `today + SEEDED_TRIP_START_OFFSET_DAYS` computed at seed time — so an account
 * generated today and one generated in March both read correctly. Nothing here
 * may contain a written calendar date; that is the whole point of the function.
 *
 * `planSummary` stays null. It is the structured snapshot the UI renders in
 * place of the prose, and inventing one would mean this fixture asserting
 * day counts and totals it did not compute.
 *
 * Exported only so `testAccounts.test.ts` can sweep the turns for a written
 * calendar date. Nothing else calls it.
 */
export function seedTranscript(
  tripId: string,
  startISO: string,
  route: string[]
): Array<typeof chatHistory.$inferInsert> {
  const from = route[0] ?? 'home';
  const to = route[route.length - 1] ?? 'the coast';
  const when = humanDate(startISO);
  const shape = route.length > 1 ? route.join(' → ') : from;

  return [
    { tripId, role: 'assistant', kind: 'form_question', content: TRIP_INTENT_QUESTION.label },
    {
      tripId,
      role: 'user',
      kind: 'form_answer',
      content: `${from} to ${to}, leaving ${when}. Happy to take it slowly and stop a few nights on the way.`,
    },
    { tripId, role: 'assistant', kind: 'ai', content: `Got it — setting off ${when}.` },
    {
      tripId,
      role: 'assistant',
      kind: 'ai',
      content: `Plan is saved! Here's the shape: ${shape}. Every driving day is a comfortable one, and I've put fuel stops in where your range needs them.`,
    },
  ];
}


/** Every test account, newest first. Only ever addresses matching the pattern. */
export async function listTestAccounts(): Promise<TestAccountSummary[]> {
  const rows = await db
    .select({
      id: users.id,
      email: users.email,
      createdAt: users.createdAt,
      status: subscriptions.status,
      spend: sql<number>`(
        SELECT COALESCE(SUM(${usageEvents.costMicrocents}), 0)
        FROM ${usageEvents}
        WHERE ${usageEvents.userId} = ${users.id}
          AND ${usageEvents.provider} LIKE 'anthropic%'
      )`,
    })
    .from(users)
    .leftJoin(subscriptions, eq(subscriptions.userId, users.id))
    .where(sql`${users.email} ~* '^sam\\+trial-[a-z0-9-]{1,40}@feraltravels\\.com$'`)
    .orderBy(desc(users.createdAt));

  return rows.map((r) => ({
    id: r.id,
    email: r.email ?? '',
    createdAt: r.createdAt,
    subscriptionStatus: r.status ?? null,
    spendMicrocents: Number(r.spend ?? 0),
  }));
}

/**
 * The pending sign-in code for a test address, if one has been requested and
 * has not expired.
 *
 * Mirrors `readFixtureOtp` in `repos/testSupport.ts` — same shape, same
 * refusal, different pattern — rather than reusing it, because that one is
 * bound to `FIXTURE_EMAIL_PATTERN` and to the E2E enablement flag that is
 * hard-off on production. Widening it to cover this case would have loosened
 * the E2E guard to serve the admin panel, which is the wrong direction.
 */
export async function readTestAccountOtp(email: string): Promise<string | null> {
  assertArmed();
  const normalized = assertTestAddress(email);
  const rows = await db
    .select({ code: emailOtpCodes.code })
    .from(emailOtpCodes)
    .where(and(eq(emailOtpCodes.email, normalized), gt(emailOtpCodes.expires, new Date())))
    .orderBy(desc(emailOtpCodes.expires))
    .limit(1);
  return rows[0]?.code ?? null;
}

/** Back to day 0 of a trial: drop the subscription and alert rows, reset the clock. */
export async function resetTestAccount(email: string): Promise<void> {
  assertArmed();
  const normalized = assertTestAddress(email);
  const [user] = await db
    .select({ id: users.id })
    .from(users)
    .where(eq(users.email, normalized))
    .limit(1);
  if (!user) throw new NotATestAccountError(normalized);
  await db.delete(subscriptions).where(eq(subscriptions.userId, user.id));
  await db.delete(usageAlerts).where(eq(usageAlerts.userId, user.id));
  await db.update(users).set({ createdAt: new Date() }).where(eq(users.id, user.id));
}

/** Age an existing test account. `TRIAL_DAYS` puts it exactly on the paywall. */
export async function ageTestAccount(email: string, days = TRIAL_DAYS): Promise<void> {
  assertArmed();
  const normalized = assertTestAddress(email);
  if (!Number.isFinite(days) || days < 0 || days > 3650) throw new Error('Implausible age');
  const target = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  const updated = await db
    .update(users)
    .set({ createdAt: target })
    .where(eq(users.email, normalized))
    .returning({ id: users.id });
  if (updated.length === 0) throw new NotATestAccountError(normalized);
}

/**
 * Hard-delete a test account. Every FK in the schema cascades from `users`, so
 * trips, chat, sessions and the subscription row go with it; `usage_events`
 * detaches to null like any other deletion.
 *
 * No tombstone is written. `deleted_users` exists to answer "did this address
 * ever have an account" and "who is churning" — a disposable account we made
 * ourselves is noise in both answers.
 */
export async function deleteTestAccount(email: string): Promise<void> {
  assertArmed();
  const normalized = assertTestAddress(email);
  const deleted = await db
    .delete(users)
    .where(eq(users.email, normalized))
    .returning({ id: users.id });
  if (deleted.length === 0) throw new NotATestAccountError(normalized);
  await db.delete(emailOtpCodes).where(eq(emailOtpCodes.email, normalized));
}
