import { isTestRequestAuthorized } from '@/server/auth/test-endpoints';
import { readFixtureOtp } from '@/server/repos/testSupport';

/**
 * TEST-ONLY: return the pending OTP for a fixture address so the E2E suite can
 * type it into the real verify UI. 404 unless test endpoints are enabled —
 * which is ALWAYS false on Vercel production, with no override.
 *
 * This is not a sign-in bypass. It mints nothing and grants nothing: the code
 * still has to be generated by a real /login request, submitted through the
 * real six-box verify form, and validated by the real verifyOtpCode path with
 * its expiry and attempt limits intact. What it removes is the mailbox, not a
 * step of authentication.
 *
 * Three guards, all of which must hold:
 *   1. E2E_TEST_ENDPOINTS=1, and never on VERCEL_ENV=production.
 *   2. the per-run HMAC secret in x-e2e-test-secret (CI sets one because the
 *      preview URL is internet-reachable).
 *   3. the address matches FIXTURE_EMAIL_PATTERN — a hardcoded shape on a
 *      subdomain with no MX, so it can never be a real person's.
 */
export async function GET(req: Request) {
  if (!isTestRequestAuthorized(req)) return new Response('Not found', { status: 404 });
  const email = new URL(req.url).searchParams.get('email');
  if (!email) return Response.json({ error: 'email is required' }, { status: 400 });
  try {
    const code = await readFixtureOtp(email);
    // 200 with code:null means "not written yet" — the caller polls.
    return Response.json({ code });
  } catch (err) {
    return Response.json(
      { error: err instanceof Error ? err.message : String(err) },
      { status: 400 },
    );
  }
}
