/**
 * Regenerate the canonical trip fixture from a real trip in the database.
 *
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/extract-canonical-trip.ts <tripId>
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/extract-canonical-trip.ts <tripId> --apply
 *
 * DRY RUN BY DEFAULT, like `trial-account`: without `--apply` it prints what it
 * found and writes nothing.
 *
 * WHY A SCRIPT AND NOT A ONE-OFF. The fixture is extracted from a trip a person
 * actually planned, because that is the only way to get real road geometry and
 * real Google places into it. That provenance is worth keeping executable: when
 * the trip is improved, or the schema grows a column the fixture should carry,
 * the answer is to re-run this rather than to hand-edit 300 lines of generated
 * data and hope.
 *
 * WHAT IT STRIPS. Ids, the owner, timestamps, chat. What lands in the fixture is
 * a shape, not a person's trip — see the header of
 * `src/server/fixtures/canonicalTrip.ts`.
 *
 * WHAT IT CONVERTS. Two things, and both matter more than they look:
 *   - Geometry becomes an ENCODED POLYLINE. The raw GeoJSON is 135 KB; encoded
 *     it is 20 KB and decodes to the same road. A fixture nobody can open is a
 *     fixture nobody checks.
 *   - `fuel_stops_updated_at` becomes an AGE IN HOURS. A stored timestamp would
 *     start fresh and quietly go stale, and the test asserting "a cached day is
 *     not re-searched" would pass, then fail, for reasons that have nothing to
 *     do with the code.
 */
import 'dotenv/config';
import postgres from 'postgres';
import { writeFileSync } from 'node:fs';
import { encodePolyline } from '../src/lib/polyline';

const FRESH_HOURS = 1;
const STALE_HOURS = 200;

async function main() {
  const tripId = process.argv[2];
  const apply = process.argv.includes('--apply');
  if (!tripId) {
    console.error('Usage: extract-canonical-trip.ts <tripId> [--apply]');
    process.exit(1);
  }

  const sql = postgres(process.env.DATABASE_URL!, { ssl: 'require' });
  try {
    const [trip] = await sql`select * from trips where id = ${tripId}`;
    if (!trip) throw new Error(`no trip ${tripId}`);
    const legs = await sql`select * from legs where trip_id = ${tripId} order by sort_order`;
    const stops = legs.length
      ? await sql`select * from stops where leg_id = any(${legs.map((l) => l.id)}) order by leg_id, sort_order`
      : [];

    console.log(`${trip.name}: ${legs.length} legs, ${stops.length} stops`);
    console.log(`  drive ${legs.filter((l) => l.leg_type === 'drive').length} · base ${legs.filter((l) => l.leg_type === 'rest').length}`);
    console.log(`  geometry on ${legs.filter((l) => l.geometry).length}/${legs.length}`);
    console.log(`  fuel states: ${[...new Set(legs.map((l) => l.fuel_status))].join(', ')}`);

    if (!apply) {
      console.log('\nDRY RUN — nothing written. Re-run with --apply.');
      return;
    }

    const geometry = legs.map((l) =>
      l.geometry?.coordinates
        ? encodePolyline(l.geometry.coordinates.map(([lng, lat]: [number, number]) => ({ lat, lng })))
        : null
    );
    writeFileSync(
      'src/server/fixtures/canonicalTripGeometry.ts',
      `// GENERATED by scripts/extract-canonical-trip.ts — do not hand-edit.\n` +
        `export const CANONICAL_LEG_GEOMETRY: readonly (string | null)[] = [\n` +
        geometry.map((g) => `  ${JSON.stringify(g)},`).join('\n') +
        `\n];\n`
    );
    console.log('\nWrote src/server/fixtures/canonicalTripGeometry.ts');
    console.log('Leg data in canonicalTrip.ts is hand-maintained — update CANONICAL_LEGS to match,');
    console.log('then run: npx vitest run src/server/fixtures/canonicalTrip.test.ts');
  } finally {
    await sql.end();
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
