#!/usr/bin/env bash
#
# Assemble the whole open bug campaign into ONE brief and hand it to Claude Code.
#
# ── Why this exists ────────────────────────────────────────────────────────
#
# The work is written down across three prompt files under docs/bugs/, and they
# are not independent: item 9 amends item 4, item 5 deletes code that item 10
# then edits, and item 11 changes a formatter that items 10 and 4 both render
# through. Handing them over one file at a time invites exactly the failure the
# separate files were meant to avoid — an agent fixing item 10 against a
# StopsSection that item 5 was supposed to have already gutted, or building the
# receipts UI that item 9 cancels.
#
# So this emits a single ordered brief: the ground rules, the decisions already
# made (so they are not re-litigated), the interlocks and the order they force,
# the documentation that is currently WRONG and must not be trusted, then the
# three prompt files in full.
#
# ── Usage ──────────────────────────────────────────────────────────────────
#
#   scripts/handoff-bug-campaign.sh              assemble, copy to clipboard, print the path
#   scripts/handoff-bug-campaign.sh --launch     assemble, then start `claude` with it
#   scripts/handoff-bug-campaign.sh --print      assemble, write it to stdout (for piping)
#
# The brief lands in .handoff/ at the repo root, which this script adds to
# .gitignore itself if it is not already there. It is regenerated every run, so
# editing it is pointless — edit the docs/bugs/ files and re-run.

set -euo pipefail

# Resolve the repo root from THIS script's location rather than $PWD, so the
# script works from any directory and does not depend on being run from the
# repo root.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

MODE="copy"
case "${1:-}" in
  --launch) MODE="launch" ;;
  --print)  MODE="print" ;;
  "")       MODE="copy" ;;
  *)
    echo "Unknown argument: $1" >&2
    echo "Usage: $0 [--launch|--print]" >&2
    exit 2
    ;;
esac

# The prompt files, in the order they belong in the brief.
PROMPTS=(
  "docs/bugs/onboarding-fix-prompt.md"
  "docs/bugs/mobile-web-nav-units-prompt.md"
  "docs/bugs/paywall-per-user-testing-prompt.md"
  "docs/bugs/ios-ci-cheap-wins-prompt.md"
)

# Fail loudly and name what is missing, rather than emitting a brief with a
# silent hole in it.
missing=()
for f in "${PROMPTS[@]}"; do
  [[ -f "$f" ]] || missing+=("$f")
done
if (( ${#missing[@]} > 0 )); then
  echo "Missing prompt file(s):" >&2
  printf '  %s\n' "${missing[@]}" >&2
  exit 1
fi

OUT_DIR="$REPO_ROOT/.handoff"
OUT="$OUT_DIR/campaign-brief.md"
mkdir -p "$OUT_DIR"

# Keep the generated brief out of git without anyone having to remember to.
if ! grep -qx '.handoff/' .gitignore 2>/dev/null; then
  printf '\n# Generated by scripts/handoff-bug-campaign.sh\n.handoff/\n' >> .gitignore
  echo "Added .handoff/ to .gitignore"
fi

# Real repository state, read at generation time. An agent picking this up
# needs to know which branch it is on and whether the tree is dirty — those
# are the two facts most likely to make its first command wrong.
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
HEAD_SHA="$(git rev-parse --short HEAD)"
if [[ -n "$(git status --porcelain)" ]]; then
  TREE_STATE="DIRTY — uncommitted changes present (see \`git status\` before you start)"
else
  TREE_STATE="clean"
fi
GENERATED_AT="$(date '+%Y-%m-%d %H:%M %Z')"

{
cat <<HEADER
# Feral Travels — open bug campaign, items 1–13 plus CI

Generated $GENERATED_AT by \`scripts/handoff-bug-campaign.sh\`. Do not edit this file; edit the
sources under \`docs/bugs/\` and re-run the script.

Branch: \`$BRANCH\` at \`$HEAD_SHA\` · working tree: $TREE_STATE

You are already working on the current \`iOS e2e (simulator)\` failure. **Finish that first.**
Everything below is queued behind it. Nothing here is urgent enough to justify leaving a red
test job half-diagnosed.

---

## Ground rules — these apply to every item

1. **Reproduce before you fix.** Every cause written in these files came from *reading* the
   source, not from watching it fail. Confirm each one in the environment where it actually
   happens and say where I am wrong. If something cannot be reproduced, say so plainly instead
   of offering a confident theory.
2. **Playwright MCP first** for anything browser-shaped — reproduce in a real browser before
   theorising or writing diagnostic scripts. It is registered in \`.mcp.json\`. If it is not
   loaded in your session, Claude in Chrome is the fallback, not an excuse to skip the step.
3. **Reliability is worth the time and the money.** Do not trim coverage, depth or fidelity to
   save CI minutes, API spend or PR wall-clock. If cost is genuinely relevant, measure it and
   give me the number — do not pre-emptively narrow a testing proposal on cost grounds.
4. **Structural guards over detection tests.** Prefer the change that makes a class of bug
   impossible over a test that notices one instance of it. Where a file says a shape has drifted
   before, that is the shape to make impossible.
5. **Mutation-check every new test.** Reintroduce the exact bug, watch the test go red, restore.
   Name which tests you checked this way. A test that has never failed has proven nothing.
6. **Never re-type file content from tool output** when editing — output can be truncated. Edit
   in place with a command or a short read-modify-write script.
7. **Commit, do not push.** Scoped commits, one per item where they separate cleanly, once
   \`tsc --noEmit\` and \`npm run test\` pass. Do not push, do not open a PR, do not merge — I do
   that.
8. **Documentation moves with the code.** If a change makes a comment, \`CLAUDE.md\` or
   \`docs/design/nocturne-reskin.md\` wrong, fix it in the same commit. Several of these items
   exist *because* that did not happen last time.

## Decisions already made — do not re-litigate these

- **Item 5:** the day card's paste row is deleted outright, not flagged off. Pasting a Maps link
  in chat is the only paste path that survives, and it must be proven to still work.
- **Item 9 supersedes item 4's receipts bullet.** Only onboarding step 1 gets the frame-7b
  treatment. Every question and answer after it stays in the transcript as ordinary chat
  bubbles. Do not build the \`Check\` + one-line receipts from §7d.
- **Item 11 reverses a documented product decision.** \`Distance\` and \`formatKmDual\` keep km as
  the primary label for imperial users on purpose ("we've decided to teach metric"). That is
  over: an imperial user sees miles and no kilometres anywhere. Change it at the source, delete
  the comments that argue the opposite.
- **Item 10's origin:** \`buildNavUrl\` omits \`origin\` when no start coords are passed, and Google
  Maps then routes from the device's current location. That is the intended behaviour — do not
  invent an origin.
- **Item 7 is future PRs only.** No self-heal, no back-fill of existing PR descriptions.

## Interlocks, and the order they force

The three files are numbered 1–12 but the *work* order is not the file order:

1. **The iOS test failure** — in flight, finish it.
2. **CI cheap wins** (\`ios-ci-cheap-wins-prompt.md\`) — same file you are already in, additive,
   independent of everything else. Fold it in while you are there.
3. **Item 1 (dead chip taps)** — it blocks the flow. Items 2, 3 and 4 cannot be exercised end to
   end until a chip tap works, so nothing about onboarding is verifiable before this lands.
4. **Item 8 (mobile-web reload flash)** — early, because every remaining item is verified at
   phone width and the flash makes that miserable. It also touches \`TripWorkspace\`'s layout
   branch, which is the same tree items 4 and 9 render inside.
5. **Items 2, 3, 4 + 9 (onboarding)** — read item 4 and item 9 together before touching either;
   9 amends 4.
6. **Item 5 (delete the paste row)** BEFORE **item 10 (navigation links)**. Both edit
   \`src/components/StopsSection.tsx\`. Doing 10 first means making the paste-row region work and
   then deleting it, and risks 10's "make the whole row a link" change getting entangled with
   affordances item 5 removes.
7. **Item 11 (units)** after item 10 — both sweep \`Itinerary.tsx\` and \`StopsSection.tsx\`, and
   item 11's fix at \`formatKmDual\`/\`Distance\` changes what item 10's rows render. One pass over
   those two files instead of three.
8. **Item 6 (vanishing fuel stop)** — the only item whose cause I do not know. Give it the time
   that needs and its own commit; do not ship a guess bundled with the rest.
9. **Items 7, 12 and 13** — independent, whenever. Item 13 (per-user paywall enforcement) is
   unblocked by nothing and blocks nothing; it is what lets the paywall be tested while the global
   switch stays off for the web demo.

## Documentation that is currently WRONG — do not trust it

Several of these bugs are downstream of comments that describe code which no longer exists.
Treat every one of these as suspect until you have read the code beneath it, and fix them as
you go:

- \`.github/workflows/ci.yml:660\` and \`:690\` — both claim the built \`.app\` is cached against a
  native fingerprint. It is not; the step below them says so itself.
- \`CLAUDE.md\`, iOS E2E paragraph — says the job runs only when something under \`mobile/\`
  changed (the diff gate was removed 2026-08-28) and that it caches the \`.app\` (it does not).
- \`src/lib/useMediaQuery.ts:16-40\` — says the post-hydration viewport flip is "sub-frame and
  invisible". It is neither, for \`TripWorkspace\`. See item 8.
- \`docs/design/nocturne-reskin.md\` §7d — the receipts treatment, cancelled by item 9.
- \`src/components/Distance.tsx\` and \`src/lib/units.ts:53-68\` — the "teach metric" reasoning,
  reversed by item 11.

## What I know I do not know

- **Item 6's cause.** Two candidate mechanisms are written out; neither is confirmed. If you come
  back with a confident story and no reproduction, I will reject it.
- **The second flash in item 8.** I saw two on reload and can only account for one.

## Report back, per item

What you reproduced, what actually caused it where that differs from what is written below, the
diff, and the real test output.

---
---

HEADER

# The prompt files, in full, with headers that survive concatenation.
i=0
for f in "${PROMPTS[@]}"; do
  i=$((i + 1))
  printf '\n\n<!-- ===================== SOURCE %d/%d: %s ===================== -->\n\n' \
    "$i" "${#PROMPTS[@]}" "$f"
  cat "$f"
  printf '\n\n---\n'
done
} > "$OUT"

LINES="$(wc -l < "$OUT" | tr -d ' ')"
BYTES="$(wc -c < "$OUT" | tr -d ' ')"

case "$MODE" in
  print)
    cat "$OUT"
    ;;
  launch)
    if ! command -v claude >/dev/null 2>&1; then
      echo "No \`claude\` on PATH — cannot launch." >&2
      echo "The brief is written to: $OUT" >&2
      exit 1
    fi
    echo "Brief: $OUT ($LINES lines, $BYTES bytes). Starting claude…"
    exec claude "$(cat "$OUT")"
    ;;
  copy)
    echo "Brief written: $OUT ($LINES lines, $BYTES bytes)"
    if command -v pbcopy >/dev/null 2>&1; then
      pbcopy < "$OUT"
      echo "Copied to the clipboard — paste it into the session that is on the iOS failure."
    else
      echo "No pbcopy on this machine; paste it from the file above."
    fi
    echo
    echo "Or hand it over directly:  $0 --launch"
    ;;
esac
