// Read the sign-in code for ${EMAIL}, AFTER the app has asked for one.
//
// ── Why the code is not simply passed in ───────────────────────────────────
//
// It used to be: scripts/ios-e2e-fixture.mjs minted a code before the
// simulator booted and handed it to Maestro as ${CODE}. That is a race with a
// 60-second timer, and CI lost it every time while a laptop could not lose it
// at all.
//
// `sendOtpCode` enforces a 60s resend cooldown, and `storeOtpCode` "deletes any
// existing codes for this address first so only one is ever valid". So when the
// flow taps "Email me a code":
//
//   inside 60s of the mint  → 429, no new code, the minted one still works
//   after  60s of the mint  → 200, the minted code is DELETED and replaced
//
// CI takes the second path: `launch.yaml` runs first and takes 53 seconds, so
// by the time sign-in taps the button the mint is ~2 minutes old. The send
// succeeded, the fixture's code was deleted, and the app typed six digits that
// no longer existed — "Invalid or expired code", surfacing two steps later as
// `Assertion is false: ".*E2E Fixture Trip.*" is visible`.
//
// AND IT COULD NEVER HAVE FAILED LOCALLY, which is worth knowing because it is
// why this shipped. `email_otp_codes.created_at` is a `timestamp` WITHOUT time
// zone: Postgres stores the server's local wall clock, and drizzle parses it
// back as UTC. On a database that is not in UTC those disagree, the computed
// age comes out NEGATIVE, and the cooldown never expires — every resend is a
// 429 forever, so the pre-minted code always survived. The local pass was not
// luck about timing; it was a second bug hiding the first. Neon runs UTC, so
// production and CI are unaffected. scripts/ios-e2e-local.sh now pins the local
// cluster to UTC so a local run can reach the same branch CI does.
//
// Reading the code HERE removes the race rather than widening it. This runs
// after the verify screen is on screen, and the app only reaches that screen
// once its own send has resolved (sign-in.tsx: `goToCodeStep` is called after
// `await requestOtp`, or on the 429 path). So whichever send won, the row this
// reads is the one the server will actually accept.
//
// Nothing is bypassed, exactly as before: the code was generated by the real
// `sendOtpCode`, is stored with its real expiry, and is about to be typed into
// the real six-box form for the real `verifyOtpCode`. `/api/test/otp` replaces
// the INBOX, not a step of authentication, and it refuses any address outside
// FIXTURE_EMAIL_PATTERN.

var headers = { 'content-type': 'application/json' };
// Set on a deployed preview, where /api/test/* is locked by a per-run HMAC.
// Unset locally, where there is nothing to lock out.
if (typeof TEST_SECRET !== 'undefined' && TEST_SECRET) {
  headers['x-e2e-test-secret'] = TEST_SECRET;
}

var res = http.post(BASE_URL + '/api/test/otp', {
  headers: headers,
  body: JSON.stringify({ email: EMAIL }),
});

if (!res.ok) {
  // 404 here is the endpoint being off (E2E_TEST_ENDPOINTS) or the secret not
  // matching — not a missing route, which is what it looks like.
  throw new Error(
    'Could not read the OTP for ' + EMAIL + ' from ' + BASE_URL +
      ' — HTTP ' + res.status + '. A 404 means E2E_TEST_ENDPOINTS=1 is missing on the ' +
      'target, or x-e2e-test-secret does not match E2E_TEST_ENDPOINTS_SECRET.'
  );
}

var body = JSON.parse(res.body);
if (!body.code) {
  throw new Error(
    'No pending code for ' + EMAIL + '. The app reached the verify screen, so a ' +
      'send resolved — the row is gone, which means something consumed or deleted it.'
  );
}

output.code = body.code;
