import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('server-only', () => ({}));
vi.mock('@/server/db/client', async () => (await import('./harness')).clientModule());

import { eq } from 'drizzle-orm';
import { legs, pois, links, stops, trips, users } from '@/server/db/schema';
import {
  addLeg,
  cloneTrip,
  createTrip,
  deleteTrip,
  getTripFull,
  listTripsForUser,
  setDeclaredFuelState,
  updateTripPosition,
} from '@/server/repos/trips';
import { addRoute, addRouteLink, getRoute, getRoutesForLeg } from '@/server/repos/routes';
import { addStop, getStop, getStopsForLeg, updateStop } from '@/server/repos/stops';
import { addTask, getTask, getTasksForTrip, updateTask } from '@/server/repos/tasks';
import { getPoisForTrip } from '@/server/repos/pois';
import { pgError, rawQuery, resetDb, seedUser, testDb } from './harness';

/**
 * Trips and everything that hangs off one, through the real repos against a
 * real Postgres: what is written comes back exactly, and deleting a trip (or
 * its owner) takes the dependent rows with it, as the FKs in schema.ts say.
 */

beforeEach(resetDb);

const GEOMETRY = {
  type: 'LineString' as const,
  coordinates: [
    [-3.7038, 40.4168],
    [-0.3763, 39.4699],
  ] as [number, number][],
};

async function tripWithLeg() {
  const user = await seedUser();
  const trip = await createTrip({ userId: user.id, name: 'Spain loop', startDate: '2026-03-01' });
  const legId = await addLeg({
    tripId: trip.id,
    title: 'ignored, derived from the endpoints',
    startName: 'Madrid',
    endName: 'Valencia',
    startLat: 40.4168,
    startLng: -3.7038,
    endLat: 39.4699,
    endLng: -0.3763,
    distanceKm: 356.4,
    driveTimeMinutes: 215,
    geometry: GEOMETRY,
  });
  return { user, trip, legId };
}

describe('trips', () => {
  it('a date column comes back as the same calendar day, in any process timezone', async () => {
    const before = process.env.TZ;
    // Ahead of UTC, so a date turned into a local-midnight Date and back
    // would land on the day before.
    process.env.TZ = 'Pacific/Auckland';
    try {
      const user = await seedUser();
      const trip = await createTrip({
        userId: user.id,
        name: 'Date check',
        startDate: '2026-03-01',
        endDate: '2026-03-09',
      });
      expect(trip.start_date_parsed).toBe('2026-03-01');
      expect(trip.end_date_parsed).toBe('2026-03-09');
      const full = await getTripFull(trip.id);
      expect(full?.start_date_parsed).toBe('2026-03-01');
      expect(full?.end_date_parsed).toBe('2026-03-09');
      const [stored] = await rawQuery<{ d: string }>(
        `select start_date_parsed::text as d from trips where id = $1`,
        [trip.id],
      );
      expect(stored.d).toBe('2026-03-01');
    } finally {
      if (before === undefined) delete process.env.TZ;
      else process.env.TZ = before;
    }
  });

  it('the enum column takes its default and reads back as the value written', async () => {
    const { db } = await testDb();
    const user = await seedUser();
    const trip = await createTrip({ userId: user.id, name: 'Enum check' });
    expect(trip.trip_status).toBe('draft');
    await db.update(trips).set({ tripStatus: 'paused' }).where(eq(trips.id, trip.id));
    expect((await getTripFull(trip.id))?.trip_status).toBe('paused');
    const err = await pgError(
      db.execute(`update trips set trip_status = 'cancelled' where id = '${trip.id}'` as never),
    );
    expect(err.code).toBe('22P02'); // invalid_text_representation: not in the enum
  });

  it('trip_name_ci_key is generated by Postgres as lower(trim(name))', async () => {
    const user = await seedUser();
    const trip = await createTrip({ userId: user.id, name: '  Big Sur RUN ' });
    const [row] = await rawQuery<{ k: string; generated: string }>(
      `select t.trip_name_ci_key as k, c.is_generated as generated
         from trips t, information_schema.columns c
        where t.id = $1 and c.table_name = 'trips' and c.column_name = 'trip_name_ci_key'`,
      [trip.id],
    );
    expect(row).toEqual({ k: 'big sur run', generated: 'ALWAYS' });
  });

  it('the unique index refuses a second trip whose name differs only in case and spaces', async () => {
    const { db } = await testDb();
    const user = await seedUser();
    await createTrip({ userId: user.id, name: 'Coast Road' });
    // Straight insert: past the repo's friendly pre-check, which is not the
    // backstop. The index is.
    const err = await pgError(
      db.insert(trips).values({ userId: user.id, name: ' coast road  ' }),
    );
    expect(err.code).toBe('23505');
    expect(err.constraint).toBe('trips_user_name_unique_idx');
    // Per user, not global.
    const other = await seedUser();
    await expect(createTrip({ userId: other.id, name: 'COAST ROAD' })).resolves.toBeTruthy();
  });

  it('createTrip refuses a taken name with a 409 before it reaches the index', async () => {
    const user = await seedUser();
    await createTrip({ userId: user.id, name: 'Alps' });
    await expect(createTrip({ userId: user.id, name: ' ALPS ' })).rejects.toMatchObject({
      status: 409,
    });
  });

  it('timestamptz: the position time is the same instant whatever the session zone', async () => {
    const { client } = await testDb();
    const user = await seedUser();
    const trip = await createTrip({ userId: user.id, name: 'Clock' });
    await updateTripPosition(trip.id, 46.948, 7.4474, 'Bern');
    const utc = (await getTripFull(trip.id))!;
    await client.exec(`set time zone 'Asia/Kolkata'`);
    try {
      const kolkata = (await getTripFull(trip.id))!;
      expect(kolkata.position_updated_at).toBe(utc.position_updated_at);
      expect(kolkata.last_known_place).toBe('Bern');
      expect(kolkata.last_known_lat).toBe(46.948);
    } finally {
      await client.exec(`set time zone 'UTC'`);
    }
  });

  it('listTripsForUser returns the trip with its day count and distance', async () => {
    const { user, trip } = await tripWithLeg();
    const list = await listTripsForUser(user.id);
    expect(list.map((t) => t.id)).toEqual([trip.id]);
    expect(list[0].day_count).toBe(1);
    expect(list[0].total_distance_km).toBe(356);
  });

  it('declared fuel state round-trips', async () => {
    const { trip, legId } = await tripWithLeg();
    await setDeclaredFuelState(trip.id, { remainingRangeKm: 152.5, legId });
    const full = (await getTripFull(trip.id))!;
    expect(full.declared_range_km).toBe(152.5);
    expect(full.declared_range_leg_id).toBe(legId);
    expect(Date.parse(full.declared_range_at!)).not.toBeNaN();
  });
});

describe('legs', () => {
  it('geometry jsonb and the derived title come back as written', async () => {
    const { trip, legId } = await tripWithLeg();
    const full = (await getTripFull(trip.id))!;
    const leg = full.legs.find((l) => l.id === legId)!;
    expect(leg.geometry).toEqual(GEOMETRY);
    expect(leg.title).toBe('Madrid → Valencia');
    expect(leg.distance_km).toBe(356.4);
    expect(leg.drive_time_minutes).toBe(215);
    const [stored] = await rawQuery<{ t: string }>(
      `select jsonb_typeof(geometry->'coordinates') as t from legs where id = $1`,
      [legId],
    );
    expect(stored.t).toBe('array'); // a jsonb array, not a JSON string
  });
});

describe('routes and route_links', () => {
  it('a route and its links round-trip, and links sort under their route', async () => {
    const { legId } = await tripWithLeg();
    const route = await addRoute({
      leg_id: legId,
      label: 'Coastal',
      description: 'Via the N-332',
      distance_km: 380.2,
      surface: 'paved',
      end_lat: 39.47,
      end_lng: -0.376,
      end_name: 'Valencia',
      end_source: 'manual',
      end_source_url: 'https://maps.example/valencia',
      drive_time_minutes: 240,
      links: [{ label: 'Wikiloc', url: 'https://wikiloc.example/1', type: 'gpx' }],
    });
    await addRouteLink({ route_id: route.id, label: 'Blog', url: 'https://blog.example/n332' });
    const back = (await getRoute(route.id))!;
    expect(back).toMatchObject({
      leg_id: legId,
      sort_order: 0,
      label: 'Coastal',
      description: 'Via the N-332',
      distance_km: 380.2,
      surface: 'paved',
      status: 'option',
      end_name: 'Valencia',
      end_source: 'manual',
      end_source_url: 'https://maps.example/valencia',
      drive_time_minutes: 240,
    });
    expect(back.links.map((l) => [l.label, l.url, l.type]).sort()).toEqual([
      ['Blog', 'https://blog.example/n332', 'other'],
      ['Wikiloc', 'https://wikiloc.example/1', 'gpx'],
    ]);
    const second = await addRoute({ leg_id: legId, label: 'Inland' });
    expect(second.sort_order).toBe(1);
    expect((await getRoutesForLeg(legId)).map((r) => r.label)).toEqual(['Coastal', 'Inland']);
  });
});

describe('stops', () => {
  it('a user stop round-trips through add and update', async () => {
    const { legId } = await tripWithLeg();
    const stop = await addStop({
      leg_id: legId,
      stop_type: 'other',
      name: 'Cuenca',
      lat: 40.0704,
      lng: -2.1374,
      distance_from_start_km: 167.25,
      notes: 'Hanging houses',
      source: 'user',
      place_id: 'ChIJ-cuenca',
      google_maps_uri: 'https://maps.google.com/?cid=1',
    });
    expect(stop).toMatchObject({ sort_order: 0, status: 'option', distance_from_start_km: 167.25 });
    const updated = await updateStop(stop.id, { status: 'selected', notes: null });
    expect(updated).toMatchObject({ status: 'selected', notes: null, place_id: 'ChIJ-cuenca' });
    expect((await getStopsForLeg(legId)).map((s) => s.id)).toEqual([stop.id]);
  });

  it("a fuel stop's jsonb reason and alternatives come back exactly as Finn stored them", async () => {
    const { db } = await testDb();
    const { legId } = await tripWithLeg();
    const alternatives = [
      { name: 'Repsol Tarancón', lat: 40.01, lng: -3.0, place_id: 'p1', distance_km: 81.5 },
      { name: 'Cepsa', lat: 40.02, lng: -2.9, place_id: null, distance_km: 90 },
    ];
    const forcedReason = { kind: 'next_fuel_far' as const, gap_km: 212 };
    // Finn's writer (server/fuel.ts) needs Google; this is the row it writes.
    const [row] = await db
      .insert(stops)
      .values({
        legId,
        stopType: 'fuel',
        name: 'Shell Motilla',
        source: 'finn',
        alternatives,
        forcedReason,
      })
      .returning();
    const back = (await getStop(row.id))!;
    expect(back.alternatives).toEqual(alternatives);
    expect(back.forced_reason).toEqual(forcedReason);
  });
});

describe('tasks', () => {
  it('a task, its answer and a non-UTC due time round-trip', async () => {
    const { trip, legId } = await tripWithLeg();
    const task = await addTask({
      trip_id: trip.id,
      leg_id: legId,
      title: 'Book the ferry',
      description: 'Denia → Ibiza, with the van',
      priority: 'high',
      reference_url: 'https://ferry.example',
      reference_label: 'Baleària',
      reference_phone: '+34 900 000 000',
      created_by: 'penny',
      due_at: '2026-03-01T09:30:00+05:30',
    });
    expect(task.due_at).toBe('2026-03-01T04:00:00.000Z');
    await updateTask(task.id, {
      status: 'done',
      answer: 'Booked, ref AB12',
      answer_source_url: 'https://ferry.example/booking/AB12',
      answer_image_url: 'https://img.example/ticket.png',
    });
    expect(await getTask(task.id)).toMatchObject({
      leg_id: legId,
      description: 'Denia → Ibiza, with the van',
      priority: 'high',
      status: 'done',
      reference_phone: '+34 900 000 000',
      created_by: 'penny',
      answer: 'Booked, ref AB12',
      answer_source_url: 'https://ferry.example/booking/AB12',
      answer_image_url: 'https://img.example/ticket.png',
      due_at: '2026-03-01T04:00:00.000Z',
    });
    expect((await getTasksForTrip(trip.id)).map((t) => t.id)).toEqual([task.id]);
  });
});

describe('pois and links', () => {
  it('cloneTrip copies a trip with its legs, stops (jsonb intact), pois and links', async () => {
    const { db } = await testDb();
    const { user, trip, legId } = await tripWithLeg();
    const forcedReason = { kind: 'next_day_fuel_far' as const, gap_km: 301 };
    await db.insert(stops).values({ legId, stopType: 'fuel', name: 'BP', forcedReason });
    await db.insert(links).values({ legId, label: 'Campsite', url: 'https://camp.example' });
    const lastVerified = new Date('2026-02-01T12:00:00Z');
    await db.insert(pois).values({
      tripId: trip.id,
      legId,
      source: 'osm',
      name: 'Viewpoint',
      lat: 39.9,
      lng: -1.2,
      rating: 4.5,
      lastVerified,
    });
    const copyId = await cloneTrip(trip.id, user.id);
    const copy = (await getTripFull(copyId))!;
    expect(copy.name).toBe('Spain loop (copy)');
    expect(copy.start_date_parsed).toBe('2026-03-01');
    expect(copy.legs).toHaveLength(1);
    const copyLeg = copy.legs[0];
    expect(copyLeg.id).not.toBe(legId);
    expect(copyLeg.geometry).toEqual(GEOMETRY);
    const copyStops = await getStopsForLeg(copyLeg.id);
    expect(copyStops.map((s) => s.forced_reason)).toEqual([forcedReason]);
    expect(copyLeg.links.map((l) => [l.label, l.url])).toEqual([['Campsite', 'https://camp.example']]);
    expect((await getPoisForTrip(trip.id))[0]).toMatchObject({
      leg_id: legId,
      source: 'osm',
      name: 'Viewpoint',
      rating: 4.5,
      last_verified: lastVerified.toISOString(),
    });
    const copyPois = await getPoisForTrip(copyId);
    expect(copyPois).toHaveLength(1);
    // last_verified is not asserted on the copy: cloneTrip does not carry it.
    expect(copyPois[0]).toMatchObject({ leg_id: copyLeg.id, name: 'Viewpoint', rating: 4.5 });
  });
});

describe('cascades', () => {
  async function counts(tripId: string) {
    const [row] = await rawQuery<Record<string, number>>(
      `select
         (select count(*)::int from legs where trip_id = $1) as legs,
         (select count(*)::int from stops s join legs l on l.id = s.leg_id where l.trip_id = $1) as stops,
         (select count(*)::int from routes) as routes,
         (select count(*)::int from route_links) as route_links,
         (select count(*)::int from tasks where trip_id = $1) as tasks,
         (select count(*)::int from pois where trip_id = $1) as pois,
         (select count(*)::int from links) as links,
         (select count(*)::int from chat_history where trip_id = $1) as chat`,
      [tripId],
    );
    return row;
  }

  async function fullTrip() {
    const { db } = await testDb();
    const { user, trip, legId } = await tripWithLeg();
    const route = await addRoute({ leg_id: legId, label: 'A' });
    await addRouteLink({ route_id: route.id, label: 'x', url: 'https://x.example' });
    await addStop({ leg_id: legId, stop_type: 'other', name: 'Stop' });
    await addTask({ trip_id: trip.id, leg_id: legId, title: 'Task' });
    await db.insert(pois).values({ tripId: trip.id, legId, source: 'osm', name: 'P', lat: 1, lng: 1 });
    await db.insert(links).values({ legId, label: 'L', url: 'https://l.example' });
    return { user, trip };
  }

  it('deleting a trip takes its legs, routes, route links, stops, tasks, pois and links', async () => {
    const { trip } = await fullTrip();
    expect(await counts(trip.id)).toEqual({
      legs: 1, stops: 1, routes: 1, route_links: 1, tasks: 1, pois: 1, links: 1, chat: 0,
    });
    await deleteTrip(trip.id);
    expect(await counts(trip.id)).toEqual({
      legs: 0, stops: 0, routes: 0, route_links: 0, tasks: 0, pois: 0, links: 0, chat: 0,
    });
  });

  it('deleting a user takes their trips and everything under them', async () => {
    const { db } = await testDb();
    const { user, trip } = await fullTrip();
    await db.delete(users).where(eq(users.id, user.id));
    expect(await getTripFull(trip.id)).toBeNull();
    expect((await counts(trip.id)).legs).toBe(0);
    expect((await rawQuery(`select 1 from routes`)).length).toBe(0);
  });

  it('deleting a leg takes its stops but leaves the trip', async () => {
    const { db } = await testDb();
    const { trip } = await fullTrip();
    await db.delete(legs).where(eq(legs.tripId, trip.id));
    expect(await counts(trip.id)).toMatchObject({ legs: 0, stops: 0, routes: 0, tasks: 0 });
    expect(await getTripFull(trip.id)).not.toBeNull();
  });
});
